
/*
Copyright (c) 2011 Sencha Inc. - Author: Nicolas Garcia Belmonte (http://philogb.github.com/)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

 */
 
 (function(){window.$jit=function(a){var a=a||window,b;for(b in $jit)$jit[b].$extend&&(a[b]=$jit[b])};$jit.version="2.0.1";var g=function(a){return document.getElementById(a)};g.empty=function(){};g.extend=function(a,b){for(var c in b||{})a[c]=b[c];return a};g.lambda=function(a){return"function"==typeof a?a:function(){return a}};g.time=Date.now||function(){return+new Date};g.splat=function(a){var b=g.type(a);return b?"array"!=b?[a]:a:[]};g.type=function(a){var b=g.type.s.call(a).match(/^\[object\s(.*)\]$/)[1].toLowerCase();
return"object"!=b?b:a&&a.$$family?a.$$family:a&&a.nodeName&&1==a.nodeType?"element":b};g.type.s=Object.prototype.toString;g.each=function(a,b){if("object"==g.type(a))for(var c in a)b(a[c],c);else{c=0;for(var d=a.length;c<d;c++)b(a[c],c)}};g.indexOf=function(a,b){if(Array.indexOf)return a.indexOf(b);for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1};g.map=function(a,b){var c=[];g.each(a,function(a,e){c.push(b(a,e))});return c};g.reduce=function(a,b,c){var d=a.length;if(0==d)return c;for(var e=
3==arguments.length?c:a[--d];d--;)e=b(e,a[d]);return e};g.merge=function(){for(var a={},b=0,c=arguments.length;b<c;b++){var d=arguments[b];if("object"==g.type(d))for(var e in d){var f=d[e],h=a[e];a[e]=h&&"object"==g.type(f)&&"object"==g.type(h)?g.merge(h,f):g.unlink(f)}}return a};g.unlink=function(a){var b;switch(g.type(a)){case "object":b={};for(var c in a)b[c]=g.unlink(a[c]);break;case "array":b=[];c=0;for(var d=a.length;c<d;c++)b[c]=g.unlink(a[c]);break;default:return a}return b};g.zip=function(){if(0===
arguments.length)return[];for(var a=0,b=[],c=arguments.length,d=arguments[0].length;a<d;a++){for(var e=0,f=[];e<c;e++)f.push(arguments[e][a]);b.push(f)}return b};g.rgbToHex=function(a,b){if(3>a.length)return null;if(4==a.length&&0==a[3]&&!b)return"transparent";for(var c=[],d=0;3>d;d++){var e=(a[d]-0).toString(16);c.push(1==e.length?"0"+e:e)}return b?c:"#"+c.join("")};g.hexToRgb=function(a){if(7!=a.length){a=a.match(/^#?(\w{1,2})(\w{1,2})(\w{1,2})$/);a.shift();if(3!=a.length)return null;for(var b=
[],c=0;3>c;c++){var d=a[c];1==d.length&&(d+=d);b.push(parseInt(d,16))}return b}a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]};g.destroy=function(a){g.clean(a);a.parentNode&&a.parentNode.removeChild(a);a.clearAttributes&&a.clearAttributes()};g.clean=function(a){for(var a=a.childNodes,b=0,c=a.length;b<c;b++)g.destroy(a[b])};g.addEvent=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c)};g.addEvents=function(a,b){for(var c in b)g.addEvent(a,c,b[c])};g.hasClass=
function(a,b){return-1<(" "+a.className+" ").indexOf(" "+b+" ")};g.addClass=function(a,b){g.hasClass(a,b)||(a.className=a.className+" "+b)};g.removeClass=function(a,b){a.className=a.className.replace(RegExp("(^|\\s)"+b+"(?:\\s|$)"),"$1")};g.getPos=function(a){for(var b=a,c=0,d=0;b&&!/^(?:body|html)$/i.test(b.tagName);)c+=b.offsetLeft,d+=b.offsetTop,b=b.offsetParent;for(var e=b=0;a&&!/^(?:body|html)$/i.test(a.tagName);)b+=a.scrollLeft,e+=a.scrollTop,a=a.parentNode;return{x:c-b,y:d-e}};g.event={get:function(a,
b){b=b||window;return a||b.event},getWheel:function(a){return a.wheelDelta?a.wheelDelta/120:-(a.detail||0)/3},isRightClick:function(a){return 3==a.which||2==a.button},getPos:function(a,b){var b=b||window,a=a||b.event,c=b.document,c=c.documentElement||c.body;a.touches&&a.touches.length&&(a=a.touches[0]);return{x:a.pageX||a.clientX+c.scrollLeft,y:a.pageY||a.clientY+c.scrollTop}},stop:function(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0;a.preventDefault?a.preventDefault():a.returnValue=
!1}};$jit.util=$jit.id=g;var i=function(a){var a=a||{},b=function(){for(var a in this)"function"!=typeof this[a]&&(this[a]=g.unlink(this[a]));this.constructor=b;if(i.prototyping)return this;a=this.initialize?this.initialize.apply(this,arguments):this;this.$$family="class";return a},c;for(c in i.Mutators)a[c]&&(a=i.Mutators[c](a,a[c]),delete a[c]);g.extend(b,this);b.constructor=i;b.prototype=a;return b};i.Mutators={Implements:function(a,b){g.each(g.splat(b),function(b){i.prototyping=b;var b="function"==
typeof b?new b:b,d;for(d in b)d in a||(a[d]=b[d]);delete i.prototyping});return a}};g.extend(i,{inherit:function(a,b){for(var c in b){var d=b[c],e=a[c],f=g.type(d);e&&"function"==f?d!=e&&i.override(a,c,d):a[c]="object"==f?g.merge(e,d):d}return a},override:function(a,b,c){var d=i.prototyping;d&&a[b]!=d[b]&&(d=null);a[b]=function(){var e=this.parent;this.parent=d?d[b]:a[b];var f=c.apply(this,arguments);this.parent=e;return f}}});i.prototype.implement=function(){var a=this.prototype;g.each(Array.prototype.slice.call(arguments||
[]),function(b){i.inherit(a,b)});return this};$jit.Class=i;$jit.json={prune:function(a,b){this.each(a,function(a,d){d==b&&a.children&&(delete a.children,a.children=[])})},getParent:function(a,b){if(a.id==b)return!1;var c=a.children;if(c&&0<c.length)for(var d=0;d<c.length;d++){if(c[d].id==b)return a;var e=this.getParent(c[d],b);if(e)return e}return!1},getSubtree:function(a,b){if(a.id==b)return a;for(var c=0,d=a.children;d&&c<d.length;c++){var e=this.getSubtree(d[c],b);if(null!=e)return e}return null},
eachLevel:function(a,b,c,d){if(b<=c&&(d(a,b),a.children))for(var e=0,a=a.children;e<a.length;e++)this.eachLevel(a[e],b+1,c,d)},each:function(a,b){this.eachLevel(a,0,Number.MAX_VALUE,b)}};$jit.Trans={$extend:!0,linear:function(a){return a}};var C=$jit.Trans,Q=function(a,b){b=g.splat(b);return g.extend(a,{easeIn:function(c){return a(c,b)},easeOut:function(c){return 1-a(1-c,b)},easeInOut:function(c){return 0.5>=c?a(2*c,b)/2:(2-a(2*(1-c),b))/2}})};g.each({Pow:function(a,b){return Math.pow(a,b[0]||6)},
Expo:function(a){return Math.pow(2,8*(a-1))},Circ:function(a){return 1-Math.sin(Math.acos(a))},Sine:function(a){return 1-Math.sin((1-a)*Math.PI/2)},Back:function(a,b){b=b[0]||1.618;return Math.pow(a,2)*((b+1)*a-b)},Bounce:function(a){for(var b,c=0,d=1;;c+=d,d/=2)if(a>=(7-4*c)/11){b=d*d-Math.pow((11-6*c-11*a)/4,2);break}return b},Elastic:function(a,b){return Math.pow(2,10*--a)*Math.cos(20*a*Math.PI*(b[0]||1)/3)}},function(a,b){C[b]=Q(a)});g.each(["Quad","Cubic","Quart","Quint"],function(a,b){C[a]=
Q(function(a){return Math.pow(a,[b+2])})});var F=new i({initialize:function(a){this.setOptions(a)},setOptions:function(a){this.opt=g.merge({duration:2500,fps:40,transition:C.Quart.easeInOut,compute:g.empty,complete:g.empty,link:"ignore"},a||{});return this},step:function(){var a=g.time(),b=this.opt;a<this.time+b.duration?(a=b.transition((a-this.time)/b.duration),b.compute(a)):(this.timer=clearInterval(this.timer),b.compute(1),b.complete())},start:function(){if(!this.check())return this;this.time=
0;this.startTimer();return this},startTimer:function(){var a=this,b=this.opt.fps;if(this.timer)return!1;this.time=g.time()-this.time;this.timer=setInterval(function(){a.step()},Math.round(1E3/b));return!0},pause:function(){this.stopTimer();return this},resume:function(){this.startTimer();return this},stopTimer:function(){if(!this.timer)return!1;this.time=g.time()-this.time;this.timer=clearInterval(this.timer);return!0},check:function(){return!this.timer?!0:"cancel"==this.opt.link?(this.stopTimer(),
!0):!1}}),r=function(){for(var a=arguments,b=0,c=a.length,d={};b<c;b++){var e=r[a[b]];e.$extend?g.extend(d,e):d[a[b]]=e}return d};r.Canvas={$extend:!0,injectInto:"id",type:"2D",width:!1,height:!1,useCanvas:!1,withLabels:!0,background:!1,Scene:{Lighting:{enable:!1,ambient:[1,1,1],directional:{direction:{x:-100,y:-100,z:-100},color:[0.5,0.3,0.1]}}}};r.Tree={$extend:!0,orientation:"left",subtreeOffset:8,siblingOffset:5,indent:10,multitree:!1,align:"center"};r.Node={$extend:!1,overridable:!1,type:"circle",
color:"#ccb",alpha:1,dim:3,height:20,width:90,autoHeight:!1,autoWidth:!1,lineWidth:1,transform:!0,align:"center",angularWidth:1,span:1,CanvasStyles:{}};r.Edge={$extend:!1,overridable:!1,type:"line",color:"#ccb",lineWidth:1,dim:15,alpha:1,epsilon:7,CanvasStyles:{}};r.Fx={$extend:!0,fps:40,duration:2500,transition:$jit.Trans.Quart.easeInOut,clearCanvas:!0};r.Label={$extend:!1,overridable:!1,type:"HTML",style:" ",size:10,family:"sans-serif",textAlign:"center",textBaseline:"alphabetic",color:"#fff"};
r.Tips={$extend:!1,enable:!1,type:"auto",offsetX:20,offsetY:20,force:!1,onShow:g.empty,onHide:g.empty};r.Navigation={$extend:!1,enable:!1,type:"auto",panning:!1,zooming:!1};r.NodeStyles={$extend:!1,enable:!1,type:"auto",stylesHover:!1,stylesClick:!1};r.Events={$extend:!1,enable:!1,enableForEdges:!1,type:"auto",onClick:g.empty,onRightClick:g.empty,onMouseMove:g.empty,onMouseEnter:g.empty,onMouseLeave:g.empty,onDragStart:g.empty,onDragMove:g.empty,onDragCancel:g.empty,onDragEnd:g.empty,onTouchStart:g.empty,
onTouchMove:g.empty,onTouchEnd:g.empty,onMouseWheel:g.empty};r.Controller={$extend:!0,onBeforeCompute:g.empty,onAfterCompute:g.empty,onCreateLabel:g.empty,onPlaceLabel:g.empty,onComplete:g.empty,onBeforePlotLine:g.empty,onAfterPlotLine:g.empty,onBeforePlotNode:g.empty,onAfterPlotNode:g.empty,request:!1};var s={initialize:function(a,b){this.viz=b;this.canvas=b.canvas;this.config=b.config[a];this.nodeTypes=b.fx.nodeTypes;var c=this.config.type;this.labelContainer=(this.dom="auto"==c?"Native"!=b.config.Label.type:
"Native"!=c)&&b.labels.getLabelContainer();this.isEnabled()&&this.initializePost()},initializePost:g.empty,setAsProperty:g.lambda(!1),isEnabled:function(){return this.config.enable},isLabel:function(a,b,c){var a=g.event.get(a,b),b=this.labelContainer,d=a.target||a.srcElement,a=a.relatedTarget;return c?a&&a==this.viz.canvas.getCtx().canvas&&!!d&&this.isDescendantOf(d,b):this.isDescendantOf(d,b)},isDescendantOf:function(a,b){for(;a&&a.parentNode;){if(a.parentNode==b)return a;a=a.parentNode}return!1}},
n={onMouseUp:g.empty,onMouseDown:g.empty,onMouseMove:g.empty,onMouseOver:g.empty,onMouseOut:g.empty,onMouseWheel:g.empty,onTouchStart:g.empty,onTouchMove:g.empty,onTouchEnd:g.empty,onTouchCancel:g.empty},Y=new i({initialize:function(a){this.viz=a;this.canvas=a.canvas;this.edge=this.node=!1;this.registeredObjects=[];this.attachEvents()},attachEvents:function(){var a=this.canvas.getElement(),b=this;a.oncontextmenu=g.lambda(!1);g.addEvents(a,{mouseup:function(a,c){var f=g.event.get(a,c);b.handleEvent("MouseUp",
a,c,b.makeEventObject(a,c),g.event.isRightClick(f))},mousedown:function(a,c){var f=g.event.get(a,c);b.handleEvent("MouseDown",a,c,b.makeEventObject(a,c),g.event.isRightClick(f))},mousemove:function(a,c){b.handleEvent("MouseMove",a,c,b.makeEventObject(a,c))},mouseover:function(a,c){b.handleEvent("MouseOver",a,c,b.makeEventObject(a,c))},mouseout:function(a,c){b.handleEvent("MouseOut",a,c,b.makeEventObject(a,c))},touchstart:function(a,c){b.handleEvent("TouchStart",a,c,b.makeEventObject(a,c))},touchmove:function(a,
c){b.handleEvent("TouchMove",a,c,b.makeEventObject(a,c))},touchend:function(a,c){b.handleEvent("TouchEnd",a,c,b.makeEventObject(a,c))}});var c=function(a,c){var f=g.event.get(a,c),f=g.event.getWheel(f);b.handleEvent("MouseWheel",a,c,f)};!document.getBoxObjectFor&&null==window.mozInnerScreenX?g.addEvent(a,"mousewheel",c):a.addEventListener("DOMMouseScroll",c,!1)},register:function(a){this.registeredObjects.push(a)},handleEvent:function(){for(var a=Array.prototype.slice.call(arguments),b=a.shift(),
c=0,d=this.registeredObjects,e=d.length;c<e;c++)d[c]["on"+b].apply(d[c],a)},makeEventObject:function(a,b){var c=this,d=this.viz.graph,e=this.viz.fx,f=e.nodeTypes,h=e.edgeTypes;return{pos:!1,node:!1,edge:!1,contains:!1,getNodeCalled:!1,getEdgeCalled:!1,getPos:function(){var d=c.viz.canvas,e=d.getSize(),f=d.getPos(),h=d.translateOffsetX,G=d.translateOffsetY,w=d.scaleOffsetX,d=d.scaleOffsetY,i=g.event.getPos(a,b);return this.pos={x:1*(i.x-f.x-e.width/2-h)/w,y:1*(i.y-f.y-e.height/2-G)/d}},getNode:function(){if(this.getNodeCalled)return this.node;
this.getNodeCalled=!0;for(var a in d.nodes){var b=d.nodes[a],h=b&&f[b.getData("type")];if(h=h&&h.contains&&h.contains.call(e,b,this.getPos()))return this.contains=h,c.node=this.node=b}return c.node=this.node=!1},getEdge:function(){if(this.getEdgeCalled)return this.edge;this.getEdgeCalled=!0;var a={},b;for(b in d.edges){var f=d.edges[b];a[b]=!0;for(var g in f)if(!(g in a)){var G=f[g],i=G&&h[G.getData("type")];if(i=i&&i.contains&&i.contains.call(e,G,this.getPos()))return this.contains=i,c.edge=this.edge=
G}}return c.edge=this.edge=!1},getContains:function(){if(this.getNodeCalled)return this.contains;this.getNode();return this.contains}}}}),A={initializeExtras:function(){var a=new Y(this),b=this;g.each(["NodeStyles","Tips","Navigation","Events"],function(c){var d=new A.Classes[c](c,b);d.isEnabled()&&a.register(d);d.setAsProperty()&&(b[c.toLowerCase()]=d)})},Classes:{}};A.Classes.Events=new i({Implements:[s,n],initializePost:function(){this.fx=this.viz.fx;this.ntypes=this.viz.fx.nodeTypes;this.etypes=
this.viz.fx.edgeTypes;this.moved=this.touchMoved=this.touched=this.pressed=this.hovered=!1},setAsProperty:g.lambda(!0),onMouseUp:function(a,b,c,d){a=g.event.get(a,b);if(!this.moved)if(d)this.config.onRightClick(this.hovered,c,a);else this.config.onClick(this.pressed,c,a);if(this.pressed){if(this.moved)this.config.onDragEnd(this.pressed,c,a);else this.config.onDragCancel(this.pressed,c,a);this.pressed=this.moved=!1}},onMouseOut:function(a,b,c){var d=g.event.get(a,b),e;if(this.dom&&(e=this.isLabel(a,
b,!0)))this.config.onMouseLeave(this.viz.graph.getNode(e.id),c,d),this.hovered=!1;else{a=d.relatedTarget;for(b=this.canvas.getElement();a&&a.parentNode;){if(b==a.parentNode)return;a=a.parentNode}this.hovered&&(this.config.onMouseLeave(this.hovered,c,d),this.hovered=!1)}},onMouseOver:function(a,b,c){var d=g.event.get(a,b),e;if(this.dom&&(e=this.isLabel(a,b,!0)))this.hovered=this.viz.graph.getNode(e.id),this.config.onMouseEnter(this.hovered,c,d)},onMouseMove:function(a,b,c){a=g.event.get(a,b);if(this.pressed)this.moved=
!0,this.config.onDragMove(this.pressed,c,a);else if(this.dom)this.config.onMouseMove(this.hovered,c,a);else{if(this.hovered){var b=this.hovered,d=b.nodeFrom?this.etypes[b.getData("type")]:this.ntypes[b.getData("type")];if(d&&d.contains&&d.contains.call(this.fx,b,c.getPos())){this.config.onMouseMove(b,c,a);return}this.config.onMouseLeave(b,c,a);this.hovered=!1}if(this.hovered=c.getNode()||this.config.enableForEdges&&c.getEdge())this.config.onMouseEnter(this.hovered,c,a);else this.config.onMouseMove(!1,
c,a)}},onMouseWheel:function(a,b,c){this.config.onMouseWheel(c,g.event.get(a,b))},onMouseDown:function(a,b,c){var d=g.event.get(a,b);if(this.dom){if(a=this.isLabel(a,b))this.pressed=this.viz.graph.getNode(a.id)}else this.pressed=c.getNode()||this.config.enableForEdges&&c.getEdge();this.pressed&&this.config.onDragStart(this.pressed,c,d)},onTouchStart:function(a,b,c){var d=g.event.get(a,b),e;(this.touched=this.dom&&(e=this.isLabel(a,b))?this.viz.graph.getNode(e.id):c.getNode()||this.config.enableForEdges&&
c.getEdge())&&this.config.onTouchStart(this.touched,c,d)},onTouchMove:function(a,b,c){a=g.event.get(a,b);this.touched&&(this.touchMoved=!0,this.config.onTouchMove(this.touched,c,a))},onTouchEnd:function(a,b,c){a=g.event.get(a,b);if(this.touched){if(this.touchMoved)this.config.onTouchEnd(this.touched,c,a);else this.config.onTouchCancel(this.touched,c,a);this.touched=this.touchMoved=!1}}});A.Classes.Tips=new i({Implements:[s,n],initializePost:function(){if(document.body){var a=g("_tooltip")||document.createElement("div");
a.id="_tooltip";a.className="tip";g.extend(a.style,{position:"absolute",display:"none",zIndex:13E3});document.body.appendChild(a);this.tip=a;this.node=!1}},setAsProperty:g.lambda(!0),onMouseOut:function(a,b){g.event.get(a,b);if(this.dom&&this.isLabel(a,b,!0))this.hide(!0);else{for(var c=a.relatedTarget,d=this.canvas.getElement();c&&c.parentNode;){if(d==c.parentNode)return;c=c.parentNode}this.hide(!1)}},onMouseOver:function(a,b){var c;if(this.dom&&(c=this.isLabel(a,b,!1)))this.node=this.viz.graph.getNode(c.id),
this.config.onShow(this.tip,this.node,c)},onMouseMove:function(a,b,c){this.dom&&this.isLabel(a,b)&&this.setTooltipPosition(g.event.getPos(a,b));if(!this.dom){var d=c.getNode();if(d){if(this.config.force||!this.node||this.node.id!=d.id)this.node=d,this.config.onShow(this.tip,d,c.getContains());this.setTooltipPosition(g.event.getPos(a,b))}else this.hide(!0)}},setTooltipPosition:function(a){var b=this.tip,c=b.style,d=this.config;c.display="";var e=document.body.clientWidth,f=b.offsetWidth,b=b.offsetHeight,
h=d.offsetX,d=d.offsetY;c.top=(a.y+d+b>document.body.clientHeight?a.y-b-d:a.y+d)+"px";c.left=(a.x+f+h>e?a.x-f-h:a.x+h)+"px"},hide:function(a){this.tip.style.display="none";a&&this.config.onHide()}});A.Classes.NodeStyles=new i({Implements:[s,n],initializePost:function(){this.fx=this.viz.fx;this.types=this.viz.fx.nodeTypes;this.nStyles=this.config;this.nodeStylesOnHover=this.nStyles.stylesHover;this.nodeStylesOnClick=this.nStyles.stylesClick;this.hoveredNode=!1;this.fx.nodeFxAnimation=new F;this.move=
this.down=!1},onMouseOut:function(a,b){this.down=this.move=!1;if(this.hoveredNode){this.dom&&this.isLabel(a,b,!0)&&this.toggleStylesOnHover(this.hoveredNode,!1);for(var c=a.relatedTarget,d=this.canvas.getElement();c&&c.parentNode;){if(d==c.parentNode)return;c=c.parentNode}this.toggleStylesOnHover(this.hoveredNode,!1);this.hoveredNode=!1}},onMouseOver:function(a,b){var c;if(this.dom&&(c=this.isLabel(a,b,!0)))c=this.viz.graph.getNode(c.id),c.selected||(this.hoveredNode=c,this.toggleStylesOnHover(this.hoveredNode,
!0))},onMouseDown:function(a,b,c,d){if(!d){var e;this.dom&&(e=this.isLabel(a,b))?this.down=this.viz.graph.getNode(e.id):this.dom||(this.down=c.getNode());this.move=!1}},onMouseUp:function(a,b,c,d){if(!d){if(!this.move)this.onClick(c.getNode());this.down=this.move=!1}},getRestoredStyles:function(a,b){var c={},d=this["nodeStylesOn"+b],e;for(e in d)c[e]=a.styles["$"+e];return c},toggleStylesOnHover:function(a,b){this.nodeStylesOnHover&&this.toggleStylesOn("Hover",a,b)},toggleStylesOnClick:function(a,
b){this.nodeStylesOnClick&&this.toggleStylesOn("Click",a,b)},toggleStylesOn:function(a,b,c){var d=this.viz;if(c){b.styles||(b.styles=g.merge(b.data,{}));for(var e in this["nodeStylesOn"+a])c="$"+e,c in b.styles||(b.styles[c]=b.getData(e));d.fx.nodeFx(g.extend({elements:{id:b.id,properties:this["nodeStylesOn"+a]},transition:C.Quart.easeOut,duration:300,fps:40},this.config))}else a=this.getRestoredStyles(b,a),d.fx.nodeFx(g.extend({elements:{id:b.id,properties:a},transition:C.Quart.easeOut,duration:300,
fps:40},this.config))},onClick:function(a){if(a){var b=this.nodeStylesOnClick;b&&(a.selected?(this.toggleStylesOnClick(a,!1),delete a.selected):(this.viz.graph.eachNode(function(a){if(a.selected){for(var d in b)a.setData(d,a.styles["$"+d],"end");delete a.selected}}),this.toggleStylesOnClick(a,!0),a.selected=!0,delete a.hovered,this.hoveredNode=!1))}},onMouseMove:function(a,b,c){this.down&&(this.move=!0);if(!this.dom||!this.isLabel(a,b)){var d=this.nodeStylesOnHover;if(d&&!this.dom){if(this.hoveredNode&&
(a=this.types[this.hoveredNode.getData("type")])&&a.contains&&a.contains.call(this.fx,this.hoveredNode,c.getPos()))return;c=c.getNode();if((this.hoveredNode||c)&&!c.hovered)c&&!c.selected?(this.fx.nodeFxAnimation.stopTimer(),this.viz.graph.eachNode(function(a){if(a.hovered&&!a.selected){for(var b in d)a.setData(b,a.styles["$"+b],"end");delete a.hovered}}),c.hovered=!0,this.hoveredNode=c,this.toggleStylesOnHover(c,!0)):this.hoveredNode&&!this.hoveredNode.selected&&(this.fx.nodeFxAnimation.stopTimer(),
this.toggleStylesOnHover(this.hoveredNode,!1),delete this.hoveredNode.hovered,this.hoveredNode=!1)}}}});A.Classes.Navigation=new i({Implements:[s,n],initializePost:function(){this.pressed=this.pos=!1},onMouseWheel:function(a,b,c){this.config.zooming&&(g.event.stop(g.event.get(a,b)),a=1+c*(this.config.zooming/1E3),this.canvas.scale(a,a))},onMouseDown:function(a,b,c){if(this.config.panning&&!("avoid nodes"==this.config.panning&&(this.dom?this.isLabel(a,b):c.getNode()))){this.pressed=!0;this.pos=c.getPos();
var a=this.canvas,b=a.translateOffsetX,c=a.translateOffsetY,d=a.scaleOffsetY;this.pos.x*=a.scaleOffsetX;this.pos.x+=b;this.pos.y*=d;this.pos.y+=c}},onMouseMove:function(a,b,c){if(this.config.panning&&this.pressed&&!("avoid nodes"==this.config.panning&&(this.dom?this.isLabel(a,b):c.getNode()))){var a=this.pos,c=c.getPos(),d=this.canvas,e=d.translateOffsetX,f=d.translateOffsetY,b=d.scaleOffsetX,d=d.scaleOffsetY;c.x*=b;c.y*=d;c.x+=e;c.y+=f;e=c.x-a.x;a=c.y-a.y;this.pos=c;this.canvas.translate(1*e/b,1*
a/d)}},onMouseUp:function(){this.config.panning&&(this.pressed=!1)}});var u,H=function(a,b){var c=document.createElement(a),d;for(d in b)"object"==typeof b[d]?g.extend(c[d],b[d]):c[d]=b[d];"canvas"==a&&(!R&&G_vmlCanvasManager)&&(c=G_vmlCanvasManager.initElement(document.body.appendChild(c)));return c},s=typeof HTMLCanvasElement,R="object"==s||"function"==s;$jit.Canvas=u=new i({canvases:[],pos:!1,element:!1,labelContainer:!1,translateOffsetX:0,translateOffsetY:0,scaleOffsetX:1,scaleOffsetY:1,initialize:function(a,
b){this.viz=a;this.opt=this.config=b;var c="string"==g.type(b.injectInto)?b.injectInto:b.injectInto.id,d=b.type,e=c+"-label",f=g(c),h=b.width||f.offsetWidth,j=b.height||f.offsetHeight;this.id=c;var k={injectInto:c,width:h,height:j};this.element=H("div",{id:c+"-canvaswidget",style:{position:"relative",width:h+"px",height:j+"px"}});this.labelContainer=this.createLabelContainer(b.Label.type,e,k);this.canvases.push(new u.Base[d]({config:g.extend({idSuffix:"-canvas"},k),plot:function(){a.fx.plot()},resize:function(){a.refresh()}}));
if(c=b.background)k=new u.Background[c.type](a,g.extend(c,k)),this.canvases.push(new u.Base[d](k));for(d=this.canvases.length;d--;)this.element.appendChild(this.canvases[d].canvas),0<d&&this.canvases[d].plot();this.element.appendChild(this.labelContainer);f.appendChild(this.element);var m=null,t=this;g.addEvent(window,"scroll",function(){clearTimeout(m);m=setTimeout(function(){t.getPos(!0)},500)})},getCtx:function(a){return this.canvases[a||0].getCtx()},getConfig:function(){return this.opt},getElement:function(){return this.element},
getSize:function(a){return this.canvases[a||0].getSize()},resize:function(a,b){this.getPos(!0);this.translateOffsetX=this.translateOffsetY=0;this.scaleOffsetX=this.scaleOffsetY=1;for(var c=0,d=this.canvases.length;c<d;c++)this.canvases[c].resize(a,b);c=this.element.style;c.width=a+"px";c.height=b+"px";this.labelContainer&&(this.labelContainer.style.width=a+"px")},translate:function(a,b,c){this.translateOffsetX+=a*this.scaleOffsetX;this.translateOffsetY+=b*this.scaleOffsetY;for(var d=0,e=this.canvases.length;d<
e;d++)this.canvases[d].translate(a,b,c)},scale:function(a,b){var c=this.scaleOffsetX*a,d=this.scaleOffsetY*b,e=this.translateOffsetX*(a-1)/c,f=this.translateOffsetY*(b-1)/d;this.scaleOffsetX=c;this.scaleOffsetY=d;c=0;for(d=this.canvases.length;c<d;c++)this.canvases[c].scale(a,b,!0);this.translate(e,f,!1)},getPos:function(a){return a||!this.pos?this.pos=g.getPos(this.getElement()):this.pos},clear:function(a){this.canvases[a||0].clear()},path:function(a,b){var c=this.canvases[0].getCtx();c.beginPath();
b(c);c[a]();c.closePath()},createLabelContainer:function(a,b,c){if("HTML"==a||"Native"==a)return H("div",{id:b,style:{overflow:"visible",position:"absolute",top:0,left:0,width:c.width+"px",height:0}});if("SVG"==a){a=document.createElementNS("http://www.w3.org/2000/svg","svg:svg");a.setAttribute("width",c.width);a.setAttribute("height",c.height);var d=a.style;d.position="absolute";d.left=d.top="0px";d=document.createElementNS("http://www.w3.org/2000/svg","svg:g");d.setAttribute("width",c.width);d.setAttribute("height",
c.height);d.setAttribute("x",0);d.setAttribute("y",0);d.setAttribute("id",b);a.appendChild(d);return a}}});u.Base={};u.Base["2D"]=new i({translateOffsetX:0,translateOffsetY:0,scaleOffsetX:1,scaleOffsetY:1,initialize:function(a){this.viz=a;this.opt=a.config;this.size=!1;this.createCanvas();this.translateToCenter()},createCanvas:function(){var a=this.opt,b=a.width,c=a.height;this.canvas=H("canvas",{id:a.injectInto+a.idSuffix,width:b,height:c,style:{position:"absolute",top:0,left:0,width:b+"px",height:c+
"px"}})},getCtx:function(){return!this.ctx?this.ctx=this.canvas.getContext("2d"):this.ctx},getSize:function(){if(this.size)return this.size;var a=this.canvas;return this.size={width:a.width,height:a.height}},translateToCenter:function(a){var b=this.getSize(),c=a?b.width-a.width-2*this.translateOffsetX:b.width;height=a?b.height-a.height-2*this.translateOffsetY:b.height;b=this.getCtx();a&&b.scale(1/this.scaleOffsetX,1/this.scaleOffsetY);b.translate(c/2,height/2)},resize:function(a,b){var c=this.getSize(),
d=this.canvas,e=d.style;this.size=!1;d.width=a;d.height=b;e.width=a+"px";e.height=b+"px";R?this.translateToCenter():this.translateToCenter(c);this.translateOffsetX=this.translateOffsetY=0;this.scaleOffsetX=this.scaleOffsetY=1;this.clear();this.viz.resize(a,b,this)},translate:function(a,b,c){var d=this.scaleOffsetY;this.translateOffsetX+=a*this.scaleOffsetX;this.translateOffsetY+=b*d;this.getCtx().translate(a,b);!c&&this.plot()},scale:function(a,b,c){this.scaleOffsetX*=a;this.scaleOffsetY*=b;this.getCtx().scale(a,
b);!c&&this.plot()},clear:function(){var a=this.getSize(),b=this.translateOffsetX,c=this.translateOffsetY,d=this.scaleOffsetX,e=this.scaleOffsetY;this.getCtx().clearRect(1*(-a.width/2-b)/d,1*(-a.height/2-c)/e,1*a.width/d,1*a.height/e)},plot:function(){this.clear();this.viz.plot(this)}});u.Background={};u.Background.Circles=new i({initialize:function(a,b){this.viz=a;this.config=g.merge({idSuffix:"-bkcanvas",levelDistance:100,numberOfCircles:6,CanvasStyles:{},offset:0},b)},resize:function(a,b,c){this.plot(c)},
plot:function(a){var a=a.getCtx(),b=this.config,c=b.CanvasStyles,d;for(d in c)a[d]=c[d];d=b.numberOfCircles;b=b.levelDistance;for(c=1;c<=d;c++)a.beginPath(),a.arc(0,0,b*c,0,2*Math.PI,!1),a.stroke(),a.closePath()}});var p=function(a,b){this.theta=a||0;this.rho=b||0};$jit.Polar=p;p.prototype={getc:function(a){return this.toComplex(a)},getp:function(){return this},set:function(a){a=a.getp();this.theta=a.theta;this.rho=a.rho},setc:function(a,b){this.rho=Math.sqrt(a*a+b*b);this.theta=Math.atan2(b,a);0>
this.theta&&(this.theta+=2*Math.PI)},setp:function(a,b){this.theta=a;this.rho=b},clone:function(){return new p(this.theta,this.rho)},toComplex:function(a){var b=Math.cos(this.theta)*this.rho,c=Math.sin(this.theta)*this.rho;return a?{x:b,y:c}:new o(b,c)},add:function(a){return new p(this.theta+a.theta,this.rho+a.rho)},scale:function(a){return new p(this.theta,this.rho*a)},equals:function(a){return this.theta==a.theta&&this.rho==a.rho},$add:function(a){this.theta+=a.theta;this.rho+=a.rho;return this},
$madd:function(a){this.theta=(this.theta+a.theta)%(2*Math.PI);this.rho+=a.rho;return this},$scale:function(a){this.rho*=a;return this},isZero:function(){var a=Math.abs;return 1E-4>a(this.theta)&&1E-4>a(this.rho)},interpolate:function(a,b){var c=Math.PI,d=2*c,e=function(a){return 0>a?a%d+d:a%d},f=this.theta,h=a.theta,j=Math.abs(f-h);return{theta:j==c?f>h?e(h+(f-d-h)*b):e(h-d+(f-h)*b):j>=c?f>h?e(h+(f-d-h)*b):e(h-d+(f-(h-d))*b):e(h+(f-h)*b),rho:(this.rho-a.rho)*b+a.rho}}};p.KER=new p(0,0);var o=function(a,
b){this.x=a||0;this.y=b||0};$jit.Complex=o;o.prototype={getc:function(){return this},getp:function(a){return this.toPolar(a)},set:function(a){a=a.getc(!0);this.x=a.x;this.y=a.y},setc:function(a,b){this.x=a;this.y=b},setp:function(a,b){this.x=Math.cos(a)*b;this.y=Math.sin(a)*b},clone:function(){return new o(this.x,this.y)},toPolar:function(a){var b=this.norm(),c=Math.atan2(this.y,this.x);0>c&&(c+=2*Math.PI);return a?{theta:c,rho:b}:new p(c,b)},norm:function(){return Math.sqrt(this.squaredNorm())},
squaredNorm:function(){return this.x*this.x+this.y*this.y},add:function(a){return new o(this.x+a.x,this.y+a.y)},prod:function(a){return new o(this.x*a.x-this.y*a.y,this.y*a.x+this.x*a.y)},conjugate:function(){return new o(this.x,-this.y)},scale:function(a){return new o(this.x*a,this.y*a)},equals:function(a){return this.x==a.x&&this.y==a.y},$add:function(a){this.x+=a.x;this.y+=a.y;return this},$prod:function(a){var b=this.x,c=this.y;this.x=b*a.x-c*a.y;this.y=c*a.x+b*a.y;return this},$conjugate:function(){this.y=
-this.y;return this},$scale:function(a){this.x*=a;this.y*=a;return this},$div:function(a){var b=this.x,c=this.y,d=a.squaredNorm();this.x=b*a.x+c*a.y;this.y=c*a.x-b*a.y;return this.$scale(1/d)},isZero:function(){var a=Math.abs;return 1E-4>a(this.x)&&1E-4>a(this.y)}};o.KER=new o(0,0);$jit.Graph=new i({initialize:function(a,b,c,d){var e={klass:o,Node:{}};this.Node=b;this.Edge=c;this.Label=d;this.opt=g.merge(e,a||{});this.nodes={};this.edges={};var f=this;this.nodeList={};for(var h in y)f.nodeList[h]=
function(a){return function(){var b=Array.prototype.slice.call(arguments);f.eachNode(function(c){c[a].apply(c,b)})}}(h)},getNode:function(a){return this.hasNode(a)?this.nodes[a]:!1},get:function(a){return this.getNode(a)},getByName:function(a){for(var b in this.nodes){var c=this.nodes[b];if(c.name==a)return c}return!1},getAdjacence:function(a,b){return a in this.edges?this.edges[a][b]:!1},addNode:function(a){if(!this.nodes[a.id]){var b=this.edges[a.id]={};this.nodes[a.id]=new l.Node(g.extend({id:a.id,
name:a.name,data:g.merge(a.data||{},{}),adjacencies:b},this.opt.Node),this.opt.klass,this.Node,this.Edge,this.Label)}return this.nodes[a.id]},addAdjacence:function(a,b,c){this.hasNode(a.id)||this.addNode(a);this.hasNode(b.id)||this.addNode(b);a=this.nodes[a.id];b=this.nodes[b.id];if(!a.adjacentTo(b)){var d=this.edges[a.id]=this.edges[a.id]||{},e=this.edges[b.id]=this.edges[b.id]||{};d[b.id]=e[a.id]=new l.Adjacence(a,b,c,this.Edge,this.Label);return d[b.id]}return this.edges[a.id][b.id]},removeNode:function(a){if(this.hasNode(a)){delete this.nodes[a];
var b=this.edges[a],c;for(c in b)delete this.edges[c][a];delete this.edges[a]}},removeAdjacence:function(a,b){delete this.edges[a][b];delete this.edges[b][a]},hasNode:function(a){return a in this.nodes},empty:function(){this.nodes={};this.edges={}}});var l=$jit.Graph,y,J=function(a,b,c,d,e){var f,c=c||"current";"current"==c?f=this.data:"start"==c?f=this.startData:"end"==c&&(f=this.endData);a="$"+(a?a+"-":"")+b;return d?f[a]:!this.Config.overridable?e[b]||0:a in f?f[a]:a in this.data?this.data[a]:
e[b]||0},K=function(a,b,c,d){var d=d||"current",e;"current"==d?e=this.data:"start"==d?e=this.startData:"end"==d&&(e=this.endData);e["$"+(a?a+"-":"")+b]=c},L=function(a,b){var a="$"+(a?a+"-":""),c=this;g.each(b,function(b){b=a+b;delete c.data[b];delete c.endData[b];delete c.startData[b]})};y={getData:function(a,b,c){return J.call(this,"",a,b,c,this.Config)},setData:function(a,b,c){K.call(this,"",a,b,c)},setDataset:function(a,b){var a=g.splat(a),c;for(c in b)for(var d=0,e=g.splat(b[c]),f=a.length;d<
f;d++)this.setData(c,e[d],a[d])},removeData:function(){L.call(this,"",Array.prototype.slice.call(arguments))},getCanvasStyle:function(a,b,c){return J.call(this,"canvas",a,b,c,this.Config.CanvasStyles)},setCanvasStyle:function(a,b,c){K.call(this,"canvas",a,b,c)},setCanvasStyles:function(a,b){var a=g.splat(a),c;for(c in b)for(var d=0,e=g.splat(b[c]),f=a.length;d<f;d++)this.setCanvasStyle(c,e[d],a[d])},removeCanvasStyle:function(){L.call(this,"canvas",Array.prototype.slice.call(arguments))},getLabelData:function(a,
b,c){return J.call(this,"label",a,b,c,this.Label)},setLabelData:function(a,b,c){K.call(this,"label",a,b,c)},setLabelDataset:function(a,b){var a=g.splat(a),c;for(c in b)for(var d=0,e=g.splat(b[c]),f=a.length;d<f;d++)this.setLabelData(c,e[d],a[d])},removeLabelData:function(){L.call(this,"label",Array.prototype.slice.call(arguments))}};l.Node=new i({initialize:function(a,b,c,d,e){b={id:"",name:"",data:{},startData:{},endData:{},adjacencies:{},selected:!1,drawn:!1,exist:!1,angleSpan:{begin:0,end:0},pos:new b,
startPos:new b,endPos:new b};g.extend(this,g.extend(b,a));this.Config=this.Node=c;this.Edge=d;this.Label=e},adjacentTo:function(a){return a.id in this.adjacencies},getAdjacency:function(a){return this.adjacencies[a]},getPos:function(a){a=a||"current";if("current"==a)return this.pos;if("end"==a)return this.endPos;if("start"==a)return this.startPos},setPos:function(a,b){var b=b||"current",c;"current"==b?c=this.pos:"end"==b?c=this.endPos:"start"==b&&(c=this.startPos);c.set(a)}});l.Node.implement(y);
l.Adjacence=new i({initialize:function(a,b,c,d,e){this.nodeFrom=a;this.nodeTo=b;this.data=c||{};this.startData={};this.endData={};this.Config=this.Edge=d;this.Label=e}});l.Adjacence.implement(y);l.Util={filter:function(a){if(!a||"string"!=g.type(a))return function(){return!0};var b=a.split(" ");return function(a){for(var d=0;d<b.length;d++)if(a[b[d]])return!1;return!0}},getNode:function(a,b){return a.nodes[b]},eachNode:function(a,b,c){var c=this.filter(c),d;for(d in a.nodes)c(a.nodes[d])&&b(a.nodes[d])},
each:function(a,b,c){this.eachNode(a,b,c)},eachAdjacency:function(a,b,c){var d=a.adjacencies,c=this.filter(c),e;for(e in d){var f=d[e];if(c(f)){if(f.nodeFrom!=a){var h=f.nodeFrom;f.nodeFrom=f.nodeTo;f.nodeTo=h}b(f,e)}}},computeLevels:function(a,b,c,d){var c=c||0,e=this.filter(d);this.eachNode(a,function(a){a._flag=!1;a._depth=-1},d);a=a.getNode(b);a._depth=c;for(var f=[a];0!=f.length;){var h=f.pop();h._flag=!0;this.eachAdjacency(h,function(a){a=a.nodeTo;!1==a._flag&&e(a)&&(0>a._depth&&(a._depth=h._depth+
1+c),f.unshift(a))},d)}},eachBFS:function(a,b,c,d){var e=this.filter(d);this.clean(a);for(var f=[a.getNode(b)];0!=f.length;)a=f.pop(),a._flag=!0,c(a,a._depth),this.eachAdjacency(a,function(a){a=a.nodeTo;!1==a._flag&&e(a)&&(a._flag=!0,f.unshift(a))},d)},eachLevel:function(a,b,c,d,e){var f=a._depth,h=this.filter(e),g=this,c=!1===c?Number.MAX_VALUE-f:c;(function m(a,b,c){var e=a._depth;e>=b&&(e<=c&&h(a))&&d(a,e);e<c&&g.eachAdjacency(a,function(a){a=a.nodeTo;a._depth>e&&m(a,b,c)})})(a,b+f,c+f)},eachSubgraph:function(a,
b,c){this.eachLevel(a,0,!1,b,c)},eachSubnode:function(a,b,c){this.eachLevel(a,1,1,b,c)},anySubnode:function(a,b,c){var d=!1,b=b||g.lambda(!0),e="string"==g.type(b)?function(a){return a[b]}:b;this.eachSubnode(a,function(a){e(a)&&(d=!0)},c);return d},getSubnodes:function(a,b,c){var d=[],b=b||0,e;"array"==g.type(b)?(e=b[0],b=b[1]):(e=b,b=Number.MAX_VALUE-a._depth);this.eachLevel(a,e,b,function(a){d.push(a)},c);return d},getParents:function(a){var b=[];this.eachAdjacency(a,function(c){c=c.nodeTo;c._depth<
a._depth&&b.push(c)});return b},isDescendantOf:function(a,b){if(a.id==b)return!0;for(var c=this.getParents(a),d=!1,e=0;!d&&e<c.length;e++)d=d||this.isDescendantOf(c[e],b);return d},clean:function(a){this.eachNode(a,function(a){a._flag=!1})},getClosestNodeToOrigin:function(a,b,c){return this.getClosestNodeToPos(a,p.KER,b,c)},getClosestNodeToPos:function(a,b,c,d){var e=null,c=c||"current",b=b&&b.getc(!0)||o.KER,f=function(a,b){var c=a.x-b.x,d=a.y-b.y;return c*c+d*d};this.eachNode(a,function(a){e=null==
e||f(a.getPos(c).getc(!0),b)<f(e.getPos(c).getc(!0),b)?a:e},d);return e}};g.each("get getNode each eachNode computeLevels eachBFS clean getClosestNodeToPos getClosestNodeToOrigin".split(" "),function(a){l.prototype[a]=function(){return l.Util[a].apply(l.Util,[this].concat(Array.prototype.slice.call(arguments)))}});g.each("eachAdjacency eachLevel eachSubgraph eachSubnode anySubnode getSubnodes getParents isDescendantOf".split(" "),function(a){l.Node.prototype[a]=function(){return l.Util[a].apply(l.Util,
[this].concat(Array.prototype.slice.call(arguments)))}});l.Op={options:{type:"nothing",duration:2E3,hideLabels:!0,fps:30},initialize:function(a){this.viz=a},removeNode:function(a,b){var c=this.viz,d=g.merge(this.options,c.controller,b),e=g.splat(a),f,h,j;switch(d.type){case "nothing":for(f=0;f<e.length;f++)c.graph.removeNode(e[f]);break;case "replot":this.removeNode(e,{type:"nothing"});c.labels.clearLabels();c.refresh(!0);break;case "fade:seq":case "fade":h=this;for(f=0;f<e.length;f++)j=c.graph.getNode(e[f]),
j.setData("alpha",0,"end");c.fx.animate(g.merge(d,{modes:["node-property:alpha"],onComplete:function(){h.removeNode(e,{type:"nothing"});c.labels.clearLabels();c.reposition();c.fx.animate(g.merge(d,{modes:["linear"]}))}}));break;case "fade:con":h=this;for(f=0;f<e.length;f++)j=c.graph.getNode(e[f]),j.setData("alpha",0,"end"),j.ignore=!0;c.reposition();c.fx.animate(g.merge(d,{modes:["node-property:alpha","linear"],onComplete:function(){h.removeNode(e,{type:"nothing"});d.onComplete&&d.onComplete()}}));
break;case "iter":h=this;c.fx.sequence({condition:function(){return 0!=e.length},step:function(){h.removeNode(e.shift(),{type:"nothing"});c.labels.clearLabels()},onComplete:function(){d.onComplete&&d.onComplete()},duration:Math.ceil(d.duration/e.length)});break;default:this.doError()}},removeEdge:function(a,b){var c=this.viz,d=g.merge(this.options,c.controller,b),e="string"==g.type(a[0])?[a]:a,f,h,j;switch(d.type){case "nothing":for(f=0;f<e.length;f++)c.graph.removeAdjacence(e[f][0],e[f][1]);break;
case "replot":this.removeEdge(e,{type:"nothing"});c.refresh(!0);break;case "fade:seq":case "fade":h=this;for(f=0;f<e.length;f++)(j=c.graph.getAdjacence(e[f][0],e[f][1]))&&j.setData("alpha",0,"end");c.fx.animate(g.merge(d,{modes:["edge-property:alpha"],onComplete:function(){h.removeEdge(e,{type:"nothing"});c.reposition();c.fx.animate(g.merge(d,{modes:["linear"]}))}}));break;case "fade:con":h=this;for(f=0;f<e.length;f++)if(j=c.graph.getAdjacence(e[f][0],e[f][1]))j.setData("alpha",0,"end"),j.ignore=
!0;c.reposition();c.fx.animate(g.merge(d,{modes:["edge-property:alpha","linear"],onComplete:function(){h.removeEdge(e,{type:"nothing"});d.onComplete&&d.onComplete()}}));break;case "iter":h=this;c.fx.sequence({condition:function(){return 0!=e.length},step:function(){h.removeEdge(e.shift(),{type:"nothing"});c.labels.clearLabels()},onComplete:function(){d.onComplete()},duration:Math.ceil(d.duration/e.length)});break;default:this.doError()}},sum:function(a,b){var c=this.viz,d=g.merge(this.options,c.controller,
b),e=c.root,f;c.root=b.id||c.root;switch(d.type){case "nothing":f=c.construct(a);f.eachNode(function(a){a.eachAdjacency(function(a){c.graph.addAdjacence(a.nodeFrom,a.nodeTo,a.data)})});break;case "replot":c.refresh(!0);this.sum(a,{type:"nothing"});c.refresh(!0);break;case "fade:seq":case "fade":case "fade:con":that=this;f=c.construct(a);var h=!this.preprocessSum(f)?["node-property:alpha"]:["node-property:alpha","edge-property:alpha"];c.reposition();"fade:con"!=d.type?c.fx.animate(g.merge(d,{modes:["linear"],
onComplete:function(){c.fx.animate(g.merge(d,{modes:h,onComplete:function(){d.onComplete()}}))}})):(c.graph.eachNode(function(a){a.id!=e&&a.pos.isZero()&&(a.pos.set(a.endPos),a.startPos.set(a.endPos))}),c.fx.animate(g.merge(d,{modes:["linear"].concat(h)})));break;default:this.doError()}},morph:function(a,b,c){var c=c||{},d=this.viz,e=g.merge(this.options,d.controller,b),f=d.root,h;d.root=b.id||d.root;switch(e.type){case "nothing":h=d.construct(a);h.eachNode(function(a){var b=d.graph.hasNode(a.id);
a.eachAdjacency(function(a){var b=!!d.graph.getAdjacence(a.nodeFrom.id,a.nodeTo.id);d.graph.addAdjacence(a.nodeFrom,a.nodeTo,a.data);if(b){var b=d.graph.getAdjacence(a.nodeFrom.id,a.nodeTo.id),c;for(c in a.data||{})b.data[c]=a.data[c]}});if(b){var b=d.graph.getNode(a.id),c;for(c in a.data||{})b.data[c]=a.data[c]}});d.graph.eachNode(function(a){a.eachAdjacency(function(a){h.getAdjacence(a.nodeFrom.id,a.nodeTo.id)||d.graph.removeAdjacence(a.nodeFrom.id,a.nodeTo.id)});h.hasNode(a.id)||d.graph.removeNode(a.id)});
break;case "replot":d.labels.clearLabels(!0);this.morph(a,{type:"nothing"});d.refresh(!0);d.refresh(!0);break;case "fade:seq":case "fade":case "fade:con":that=this;h=d.construct(a);var j="node-property"in c&&g.map(g.splat(c["node-property"]),function(a){return"$"+a});d.graph.eachNode(function(a){var b=h.getNode(a.id);if(b){var b=b.data,c;for(c in b)j&&-1<g.indexOf(j,c)?a.endData[c]=b[c]:a.data[c]=b[c]}else a.setData("alpha",1),a.setData("alpha",1,"start"),a.setData("alpha",0,"end"),a.ignore=!0});
d.graph.eachNode(function(a){a.ignore||a.eachAdjacency(function(a){if(!a.nodeFrom.ignore&&!a.nodeTo.ignore){var b=h.getNode(a.nodeFrom.id),a=h.getNode(a.nodeTo.id);b.adjacentTo(a)||(a=d.graph.getAdjacence(b.id,a.id),k=!0,a.setData("alpha",1),a.setData("alpha",1,"start"),a.setData("alpha",0,"end"))}})});var k=this.preprocessSum(h),a=!k?["node-property:alpha"]:["node-property:alpha","edge-property:alpha"];a[0]+="node-property"in c?":"+g.splat(c["node-property"]).join(":"):"";a[1]=(a[1]||"edge-property:alpha")+
("edge-property"in c?":"+g.splat(c["edge-property"]).join(":"):"");"label-property"in c&&a.push("label-property:"+g.splat(c["label-property"]).join(":"));d.reposition?d.reposition():d.compute("end");d.graph.eachNode(function(a){a.id!=f&&a.pos.getp().equals(p.KER)&&(a.pos.set(a.endPos),a.startPos.set(a.endPos))});d.fx.animate(g.merge(e,{modes:[c.position||"polar"].concat(a),onComplete:function(){d.graph.eachNode(function(a){a.ignore&&d.graph.removeNode(a.id)});d.graph.eachNode(function(a){a.eachAdjacency(function(a){a.ignore&&
d.graph.removeAdjacence(a.nodeFrom.id,a.nodeTo.id)})});e.onComplete()}}))}},contract:function(a,b){var c=this.viz;!a.collapsed&&a.anySubnode(g.lambda(!0))&&(b=g.merge(this.options,c.config,b||{},{modes:["node-property:alpha:span","linear"]}),a.collapsed=!0,function e(a){a.eachSubnode(function(a){a.ignore=!0;a.setData("alpha",0,"animate"==b.type?"end":"current");e(a)})}(a),"animate"==b.type?(c.compute("end"),c.rotated&&c.rotate(c.rotated,"none",{property:"end"}),function f(b){b.eachSubnode(function(b){b.setPos(a.getPos("end"),
"end");f(b)})}(a),c.fx.animate(b)):"replot"==b.type&&c.refresh())},expand:function(a,b){if("collapsed"in a){var c=this.viz,b=g.merge(this.options,c.config,b||{},{modes:["node-property:alpha:span","linear"]});delete a.collapsed;(function e(a){a.eachSubnode(function(a){delete a.ignore;a.setData("alpha",1,"animate"==b.type?"end":"current");e(a)})})(a);"animate"==b.type?(c.compute("end"),c.rotated&&c.rotate(c.rotated,"none",{property:"end"}),c.fx.animate(b)):"replot"==b.type&&c.refresh()}},preprocessSum:function(a){var b=
this.viz;a.eachNode(function(a){b.graph.hasNode(a.id)||(b.graph.addNode(a),a=b.graph.getNode(a.id),a.setData("alpha",0),a.setData("alpha",0,"start"),a.setData("alpha",1,"end"))});var c=!1;a.eachNode(function(a){a.eachAdjacency(function(a){var d=b.graph.getNode(a.nodeFrom.id),h=b.graph.getNode(a.nodeTo.id);d.adjacentTo(h)||(a=b.graph.addAdjacence(d,h,a.data),d.startAlpha==d.endAlpha&&h.startAlpha==h.endAlpha&&(c=!0,a.setData("alpha",0),a.setData("alpha",0,"start"),a.setData("alpha",1,"end")))})});
return c}};var M={none:{render:g.empty,contains:g.lambda(!1)},circle:{render:function(a,b,c,d){d=d.getCtx();d.beginPath();d.arc(b.x,b.y,c,0,2*Math.PI,!0);d.closePath();d[a]()},contains:function(a,b,c){var d=a.x-b.x,a=a.y-b.y;return d*d+a*a<=c*c}},ellipse:{render:function(a,b,c,d,e){var e=e.getCtx(),f=1,h=1,g=1,k=1,m=0;c>d?(m=c/2,h=d/c,k=c/d):(m=d/2,f=c/d,g=d/c);e.save();e.scale(f,h);e.beginPath();e.arc(b.x*g,b.y*k,m,0,2*Math.PI,!0);e.closePath();e[a]();e.restore()},contains:function(a,b,c,d){var e=
0,f=1,h=1,g=0,k=0;c>d?(e=c/2,h=d/c):(e=d/2,f=c/d);g=(a.x-b.x)*(1/f);k=(a.y-b.y)*(1/h);return g*g+k*k<=e*e}},square:{render:function(a,b,c,d){d.getCtx()[a+"Rect"](b.x-c,b.y-c,2*c,2*c)},contains:function(a,b,c){return Math.abs(b.x-a.x)<=c&&Math.abs(b.y-a.y)<=c}},rectangle:{render:function(a,b,c,d,e){e.getCtx()[a+"Rect"](b.x-c/2,b.y-d/2,c,d)},contains:function(a,b,c,d){return Math.abs(b.x-a.x)<=c/2&&Math.abs(b.y-a.y)<=d/2}},triangle:{render:function(a,b,c,d){var d=d.getCtx(),e=b.x,f=b.y-c,h=e-c,b=b.y+
c,c=e+c;d.beginPath();d.moveTo(e,f);d.lineTo(h,b);d.lineTo(c,b);d.closePath();d[a]()},contains:function(a,b,c){return M.circle.contains(a,b,c)}},star:{render:function(a,b,c,d){var d=d.getCtx(),e=Math.PI/5;d.save();d.translate(b.x,b.y);d.beginPath();d.moveTo(c,0);for(b=0;9>b;b++)d.rotate(e),0==b%2?d.lineTo(0.200811*(c/0.525731),0):d.lineTo(c,0);d.closePath();d[a]();d.restore()},contains:function(a,b,c){return M.circle.contains(a,b,c)}}},S={line:{render:function(a,b,c){c=c.getCtx();c.beginPath();c.moveTo(a.x,
a.y);c.lineTo(b.x,b.y);c.stroke()},contains:function(a,b,c,d){var e=Math.min,f=Math.max,h=e(a.x,b.x),g=f(a.x,b.x),e=e(a.y,b.y),f=f(a.y,b.y);return c.x>=h&&c.x<=g&&c.y>=e&&c.y<=f?Math.abs(b.x-a.x)<=d?!0:Math.abs((b.y-a.y)/(b.x-a.x)*(c.x-a.x)+a.y-c.y)<=d:!1}},arrow:{render:function(a,b,c,d,e){e=e.getCtx();d&&(d=a,a=b,b=d);d=new o(b.x-a.x,b.y-a.y);d.$scale(c/d.norm());var c=new o(b.x-d.x,b.y-d.y),f=new o(-d.y/2,d.x/2),d=c.add(f),c=c.$add(f.$scale(-1));e.beginPath();e.moveTo(a.x,a.y);e.lineTo(b.x,b.y);
e.stroke();e.beginPath();e.moveTo(d.x,d.y);e.lineTo(c.x,c.y);e.lineTo(b.x,b.y);e.closePath();e.fill()},contains:function(a,b,c,d){return S.line.contains(a,b,c,d)}},hyperline:{render:function(a,b,c,d){var e,f,h,g,k;function m(a,b){return a<b?a+Math.PI>b?!1:!0:b+Math.PI>a?!0:!1}d=d.getCtx();e=a.x*b.y-a.y*b.x;f=a.squaredNorm();k=b.squaredNorm();0==e?(f=e=0,h=-1,k=g=void 0):(g=(a.y*k-b.y*f+a.y-b.y)/e,k=(b.x*f-a.x*k+b.x-a.x)/e,e=-g/2,f=-k/2,h=(g*g+k*k)/4-1,0>h?(f=e=0,h=-1,k=g=void 0):(h=Math.sqrt(h),h=
1E3<h?-1:h));1E3<g||1E3<k||0>h?(d.beginPath(),d.moveTo(a.x*c,a.y*c),d.lineTo(b.x*c,b.y*c)):(b=Math.atan2(b.y-f,b.x-e),a=Math.atan2(a.y-f,a.x-e),m=m(b,a),d.beginPath(),d.arc(e*c,f*c,h*c,b,a,m));d.stroke()},contains:g.lambda(!1)}};l.Plot={initialize:function(a,b){this.viz=a;this.config=a.config;this.node=a.config.Node;this.edge=a.config.Edge;this.animation=new F;this.nodeTypes=new b.Plot.NodeTypes;this.edgeTypes=new b.Plot.EdgeTypes;this.labels=a.labels},nodeHelper:M,edgeHelper:S,Interpolator:{map:{border:"color",
color:"color",width:"number",height:"number",dim:"number",alpha:"number",lineWidth:"number",angularWidth:"number",span:"number",valueArray:"array-number",dimArray:"array-number"},canvas:{globalAlpha:"number",fillStyle:"color",strokeStyle:"color",lineWidth:"number",shadowBlur:"number",shadowColor:"color",shadowOffsetX:"number",shadowOffsetY:"number",miterLimit:"number"},label:{size:"number",color:"color"},compute:function(a,b,c){return a+(b-a)*c},moebius:function(a,b,c,d){b=d.scale(-c);if(1>b.norm()){var c=
b.x,d=b.y,e=a.startPos.getc().moebiusTransformation(b);a.pos.setc(e.x,e.y);b.x=c;b.y=d}},linear:function(a,b,c){var b=a.startPos.getc(!0),d=a.endPos.getc(!0);a.pos.setc(this.compute(b.x,d.x,c),this.compute(b.y,d.y,c))},polar:function(a,b,c){b=a.startPos.getp(!0);c=a.endPos.getp().interpolate(b,c);a.pos.setp(c.theta,c.rho)},number:function(a,b,c,d,e){var f=a[d](b,"start"),d=a[d](b,"end");a[e](b,this.compute(f,d,c))},color:function(a,b,c,d,e){var f=g.hexToRgb(a[d](b,"start")),d=g.hexToRgb(a[d](b,"end")),
h=this.compute,c=g.rgbToHex([parseInt(h(f[0],d[0],c)),parseInt(h(f[1],d[1],c)),parseInt(h(f[2],d[2],c))]);a[e](b,c)},"array-number":function(a,b,c,d,e){for(var f=a[d](b,"start"),d=a[d](b,"end"),h=[],g=0,k=f.length;g<k;g++){var m=f[g],t=d[g];if(m.length){for(var i=0,l=m.length,z=[];i<l;i++)z.push(this.compute(m[i],t[i],c));h.push(z)}else h.push(this.compute(m,t,c))}a[e](b,h)},node:function(a,b,c,d,e,f){d=this[d];if(b)for(var h=b.length,g=0;g<h;g++){var k=b[g];this[d[k]](a,k,c,e,f)}else for(k in d)this[d[k]](a,
k,c,e,f)},edge:function(a,b,c,d,e,f){var a=a.adjacencies,h;for(h in a)this.node(a[h],b,c,d,e,f)},"node-property":function(a,b,c){this.node(a,b,c,"map","getData","setData")},"edge-property":function(a,b,c){this.edge(a,b,c,"map","getData","setData")},"label-property":function(a,b,c){this.node(a,b,c,"label","getLabelData","setLabelData")},"node-style":function(a,b,c){this.node(a,b,c,"canvas","getCanvasStyle","setCanvasStyle")},"edge-style":function(a,b,c){this.edge(a,b,c,"canvas","getCanvasStyle","setCanvasStyle")}},
sequence:function(a){var b=this,a=g.merge({condition:g.lambda(!1),step:g.empty,onComplete:g.empty,duration:200},a||{}),c=setInterval(function(){a.condition()?a.step():(clearInterval(c),a.onComplete());b.viz.refresh(!0)},a.duration)},prepare:function(a){var b=this.viz.graph,c={"node-property":{getter:"getData",setter:"setData"},"edge-property":{getter:"getData",setter:"setData"},"node-style":{getter:"getCanvasStyle",setter:"setCanvasStyle"},"edge-style":{getter:"getCanvasStyle",setter:"setCanvasStyle"}},
d={};if("array"==g.type(a))for(var e=0,f=a.length;e<f;e++){var h=a[e].split(":");d[h.shift()]=h}else for(e in a)"position"==e?d[a.position]=[]:d[e]=g.splat(a[e]);b.eachNode(function(a){a.startPos.set(a.pos);g.each(["node-property","node-style"],function(b){if(b in d)for(var e=d[b],f=0,h=e.length;f<h;f++)a[c[b].setter](e[f],a[c[b].getter](e[f]),"start")});g.each(["edge-property","edge-style"],function(b){if(b in d){var e=d[b];a.eachAdjacency(function(a){for(var d=0,f=e.length;d<f;d++)a[c[b].setter](e[d],
a[c[b].getter](e[d]),"start")})}})});return d},animate:function(a,b){var a=g.merge(this.viz.config,a||{}),c=this,d=this.viz.graph,e=this.Interpolator,f="nodefx"===a.type?this.nodeFxAnimation:this.animation,h=this.prepare(a.modes);a.hideLabels&&this.labels.hideLabels(!0);f.setOptions(g.extend(a,{$animating:!1,compute:function(f){d.eachNode(function(a){for(var c in h)e[c](a,h[c],f,b)});c.plot(a,this.$animating,f);this.$animating=!0},complete:function(){a.hideLabels&&c.labels.hideLabels(!1);c.plot(a);
a.onComplete()}})).start()},nodeFx:function(a){var b=this.viz,c=b.graph,d=this.nodeFxAnimation,e=g.merge(this.viz.config,{elements:{id:!1,properties:{}},reposition:!1}),a=g.merge(e,a||{},{onBeforeCompute:g.empty,onAfterCompute:g.empty});d.stopTimer();var f=a.elements.properties;a.elements.id?(d=g.splat(a.elements.id),g.each(d,function(a){if(a=c.getNode(a))for(var b in f)a.setData(b,f[b],"end")})):c.eachNode(function(a){for(var b in f)a.setData(b,f[b],"end")});var d=[],h;for(h in f)d.push(h);h=["node-property:"+
d.join(":")];a.reposition&&(h.push("linear"),b.compute("end"));this.animate(g.merge(a,{modes:h,type:"nodefx"}))},plot:function(a,b){var c=this.viz,d=c.graph,e=c.canvas,c=c.root,f=this;e.getCtx();a=a||this.viz.controller;a.clearCanvas&&e.clear();if(c=d.getNode(c)){var h=!!c.visited;d.eachNode(function(c){var d=c.getData("alpha");c.eachAdjacency(function(d){var g=d.nodeTo;!!g.visited===h&&(c.drawn&&g.drawn)&&(!b&&a.onBeforePlotLine(d),f.plotLine(d,e,b),!b&&a.onAfterPlotLine(d))});c.drawn&&(!b&&a.onBeforePlotNode(c),
f.plotNode(c,e,b),!b&&a.onAfterPlotNode(c));!f.labelsHidden&&a.withLabels&&(c.drawn&&0.95<=d?f.labels.plotLabel(e,c,a):f.labels.hideLabel(c,!1));c.visited=!h})}},plotTree:function(a,b,c){var d=this,e=this.viz.canvas;e.getCtx();var f=a.getData("alpha");a.eachSubnode(function(f){if(b.plotSubtree(a,f)&&f.exist&&f.drawn){var g=a.getAdjacency(f.id);!c&&b.onBeforePlotLine(g);d.plotLine(g,e,c);!c&&b.onAfterPlotLine(g);d.plotTree(f,b,c)}});a.drawn?(!c&&b.onBeforePlotNode(a),this.plotNode(a,e,c),!c&&b.onAfterPlotNode(a),
!b.hideLabels&&b.withLabels&&0.95<=f?this.labels.plotLabel(e,a,b):this.labels.hideLabel(a,!1)):this.labels.hideLabel(a,!0)},plotNode:function(a,b,c){var d=a.getData("type"),e=this.node.CanvasStyles;if("none"!=d){var f=a.getData("lineWidth"),h=a.getData("color"),g=a.getData("alpha"),k=b.getCtx();k.save();k.lineWidth=f;k.fillStyle=k.strokeStyle=h;k.globalAlpha=g;for(var m in e)k[m]=a.getCanvasStyle(m);this.nodeTypes[d].render.call(this,a,b,c);k.restore()}},plotLine:function(a,b,c){var d=a.getData("type"),
e=this.edge.CanvasStyles;if("none"!=d){var f=a.getData("lineWidth"),h=a.getData("color"),g=b.getCtx(),k=a.nodeFrom,m=a.nodeTo;g.save();g.lineWidth=f;g.fillStyle=g.strokeStyle=h;g.globalAlpha=Math.min(k.getData("alpha"),m.getData("alpha"),a.getData("alpha"));for(var t in e)g[t]=a.getCanvasStyle(t);this.edgeTypes[d].render.call(this,a,b,c);g.restore()}}};l.Plot3D=g.merge(l.Plot,{Interpolator:{linear:function(a,b,c){var b=a.startPos.getc(!0),d=a.endPos.getc(!0);a.pos.setc(this.compute(b.x,d.x,c),this.compute(b.y,
d.y,c),this.compute(b.z,d.z,c))}},plotNode:function(a,b){"none"!=a.getData("type")&&this.plotElement(a,b,{getAlpha:function(){return a.getData("alpha")}})},plotLine:function(a,b){"none"!=a.getData("type")&&this.plotElement(a,b,{getAlpha:function(){return Math.min(a.nodeFrom.getData("alpha"),a.nodeTo.getData("alpha"),a.getData("alpha"))}})},plotElement:function(a,b,c){var d=b.getCtx(),e=new Matrix4,f=b.config.Scene.Lighting,h=b.canvases[0],b=h.program,h=h.camera;a.geometry||(a.geometry=new (O3D[a.getData("type")]));
a.geometry.update(a);if(!a.webGLVertexBuffer){for(var j=[],k=[],m=[],t=0,i=a.geometry,l=0,z=i.vertices,i=i.faces,o=i.length;l<o;l++){var q=i[l],N=z[q.a],n=z[q.b],r=z[q.c],p=q.d?z[q.d]:!1,q=q.normal;j.push(N.x,N.y,N.z);j.push(n.x,n.y,n.z);j.push(r.x,r.y,r.z);p&&j.push(p.x,p.y,p.z);m.push(q.x,q.y,q.z);m.push(q.x,q.y,q.z);m.push(q.x,q.y,q.z);p&&m.push(q.x,q.y,q.z);k.push(t,t+1,t+2);p?(k.push(t,t+2,t+3),t+=4):t+=3}a.webGLVertexBuffer=d.createBuffer();d.bindBuffer(d.ARRAY_BUFFER,a.webGLVertexBuffer);d.bufferData(d.ARRAY_BUFFER,
new Float32Array(j),d.STATIC_DRAW);a.webGLFaceBuffer=d.createBuffer();d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,a.webGLFaceBuffer);d.bufferData(d.ELEMENT_ARRAY_BUFFER,new Uint16Array(k),d.STATIC_DRAW);a.webGLFaceCount=k.length;a.webGLNormalBuffer=d.createBuffer();d.bindBuffer(d.ARRAY_BUFFER,a.webGLNormalBuffer);d.bufferData(d.ARRAY_BUFFER,new Float32Array(m),d.STATIC_DRAW)}e.multiply(h.matrix,a.geometry.matrix);d.uniformMatrix4fv(b.viewMatrix,!1,e.flatten());d.uniformMatrix4fv(b.projectionMatrix,!1,h.projectionMatrix.flatten());
e=Matrix4.makeInvert(e);e.$transpose();d.uniformMatrix4fv(b.normalMatrix,!1,e.flatten());e=g.hexToRgb(a.getData("color"));e.push(c.getAlpha());d.uniform4f(b.color,e[0]/255,e[1]/255,e[2]/255,e[3]);d.uniform1i(b.enableLighting,f.enable);if(f.enable&&(f.ambient&&(c=f.ambient,d.uniform3f(b.ambientColor,c[0],c[1],c[2])),f.directional))f=f.directional,e=f.color,f=f.direction,f=(new Vector3(f.x,f.y,f.z)).normalize().$scale(-1),d.uniform3f(b.lightingDirection,f.x,f.y,f.z),d.uniform3f(b.directionalColor,e[0],
e[1],e[2]);d.bindBuffer(d.ARRAY_BUFFER,a.webGLVertexBuffer);d.vertexAttribPointer(b.position,3,d.FLOAT,!1,0,0);d.bindBuffer(d.ARRAY_BUFFER,a.webGLNormalBuffer);d.vertexAttribPointer(b.normal,3,d.FLOAT,!1,0,0);d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,a.webGLFaceBuffer);d.drawElements(d.TRIANGLES,a.webGLFaceCount,d.UNSIGNED_SHORT,0)}});l.Label={};l.Label.Native=new i({initialize:function(a){this.viz=a},plotLabel:function(a,b,c){var d=a.getCtx();b.pos.getc(!0);d.font=b.getLabelData("style")+" "+b.getLabelData("size")+
"px "+b.getLabelData("family");d.textAlign=b.getLabelData("textAlign");d.fillStyle=d.strokeStyle=b.getLabelData("color");d.textBaseline=b.getLabelData("textBaseline");this.renderLabel(a,b,c)},renderLabel:function(a,b){var c=a.getCtx(),d=b.pos.getc(!0);c.fillText(b.name,d.x,d.y+b.getData("height")/2)},hideLabel:g.empty,hideLabels:g.empty});l.Label.DOM=new i({labelsHidden:!1,labelContainer:!1,labels:{},getLabelContainer:function(){return this.labelContainer?this.labelContainer:this.labelContainer=document.getElementById(this.viz.config.labelContainer)},
getLabel:function(a){return a in this.labels&&null!=this.labels[a]?this.labels[a]:this.labels[a]=document.getElementById(a)},hideLabels:function(a){this.getLabelContainer().style.display=a?"none":"";this.labelsHidden=a},clearLabels:function(a){for(var b in this.labels)if(a||!this.viz.graph.hasNode(b))this.disposeLabel(b),delete this.labels[b]},disposeLabel:function(a){(a=this.getLabel(a))&&a.parentNode&&a.parentNode.removeChild(a)},hideLabel:function(a,b){var a=g.splat(a),c=b?"":"none",d=this;g.each(a,
function(a){if(a=d.getLabel(a.id))a.style.display=c})},fitsInCanvas:function(a,b){var c=b.getSize();return a.x>=c.width||0>a.x||a.y>=c.height||0>a.y?!1:!0}});l.Label.HTML=new i({Implements:l.Label.DOM,plotLabel:function(a,b,c){var a=b.id,d=this.getLabel(a);if(!d&&!(d=document.getElementById(a))){var d=document.createElement("div"),e=this.getLabelContainer();d.id=a;d.className="node";d.style.position="absolute";c.onCreateLabel(d,b);e.appendChild(d);this.labels[b.id]=d}this.placeLabel(d,b,c)}});l.Label.SVG=
new i({Implements:l.Label.DOM,plotLabel:function(a,b,c){var a=b.id,d=this.getLabel(a);if(!d&&!(d=document.getElementById(a))){var d=document.createElementNS("http://www.w3.org/2000/svg","svg:text"),e=document.createElementNS("http://www.w3.org/2000/svg","svg:tspan");d.appendChild(e);e=this.getLabelContainer();d.setAttribute("id",a);d.setAttribute("class","node");e.appendChild(d);c.onCreateLabel(d,b);this.labels[b.id]=d}this.placeLabel(d,b,c)}});var s={construct:function(a){var b="array"==g.type(a),
c=new l(this.graphOptions,this.config.Node,this.config.Edge,this.config.Label);if(b)for(var b=function(b){for(var d=0,e=a.length;d<e;d++)if(a[d].id==b)return a[d];return c.addNode({id:b,name:b})},d=0,e=a.length;d<e;d++){c.addNode(a[d]);var f=a[d].adjacencies;if(f)for(var h=0,j=f.length;h<j;h++){var k=f[h],m={};"string"!=typeof f[h]&&(m=g.merge(k.data,{}),k=k.nodeTo);c.addAdjacence(a[d],b(k),m)}}else(function(a,b){a.addNode(b);if(b.children)for(var c=0,d=b.children;c<d.length;c++)a.addAdjacence(b,
d[c]),arguments.callee(a,d[c])})(c,a);return c},loadJSON:function(a,b){this.json=a;this.labels&&this.labels.clearLabels&&this.labels.clearLabels(!0);this.graph=this.construct(a);this.root="array"!=g.type(a)?a.id:a[b?b:0].id},toJSON:function(a){if("tree"==(a||"tree"))var b={},b=function e(a){var b={};b.id=a.id;b.name=a.name;b.data=a.data;var c=[];a.eachSubnode(function(a){c.push(e(a))});b.children=c;return b}(this.graph.getNode(this.root));else{var b=[],c=!!this.graph.getNode(this.root).visited;this.graph.eachNode(function(a){var f=
{};f.id=a.id;f.name=a.name;f.data=a.data;var h=[];a.eachAdjacency(function(a){var b=a.nodeTo;if(!!b.visited===c){var e={};e.nodeTo=b.id;e.data=a.data;h.push(e)}});f.adjacencies=h;b.push(f);a.visited=!c})}return b}},n=$jit.Layouts={},T={label:null,compute:function(a,b,c){this.initializeLabel(c);var d=this.label,e=d.style;a.eachNode(function(a){var b=a.getData("autoWidth"),c=a.getData("autoHeight");if(b||c){delete a.data.$width;delete a.data.$height;delete a.data.$dim;var k=a.getData("width"),m=a.getData("height");
e.width=b?"auto":k+"px";e.height=c?"auto":m+"px";d.innerHTML=a.name;b=d.offsetWidth;c=d.offsetHeight;k=a.getData("type");-1===g.indexOf(["circle","square","triangle","star"],k)?(a.setData("width",b),a.setData("height",c)):(b=b>c?b:c,a.setData("width",b),a.setData("height",b),a.setData("dim",b))}})},initializeLabel:function(a){this.label||(this.label=document.createElement("div"),document.body.appendChild(this.label));this.setLabelStyles(a)},setLabelStyles:function(){g.extend(this.label.style,{visibility:"hidden",
position:"absolute",width:"auto",height:"auto"});this.label.className="jit-autoadjust-label"}};n.TM={};n.TM.SliceAndDice=new i({compute:function(a){var b=this.graph.getNode(this.clickedNode&&this.clickedNode.id||this.root);this.controller.onBeforeCompute(b);var c=this.canvas.getSize(),d=this.config,e=c.width,c=c.height;this.graph.computeLevels(this.root,0,"ignore");b.getPos(a).setc(-e/2,-c/2);b.setData("width",e,a);b.setData("height",c+d.titleHeight,a);this.computePositions(b,b,this.layout.orientation,
a);this.controller.onAfterCompute(b)},computePositions:function(a,b,c,d){var e=0;a.eachSubnode(function(a){e+=a.getData("area",d)});var f=this.config,h=a.getData("width",d),g=Math.max(a.getData("height",d)-f.titleHeight,0),a=a==b?1:b.getData("area",d)/e,k,m,i,l,w;"h"==c?(c="v",h*=a,k="height",m="y",i="x",l=f.titleHeight,w=0):(c="h",g*=a,k="width",m="x",i="y",l=0,w=f.titleHeight);var n=b.getPos(d);b.setData("width",h,d);b.setData("height",g,d);var p=0,q=this;b.eachSubnode(function(a){var e=a.getPos(d);
e[m]=p+n[m]+l;e[i]=n[i]+w;q.computePositions(b,a,c,d);p=p+a.getData(k,d)})}});n.TM.Area={compute:function(a){var a=a||"current",b=this.graph.getNode(this.clickedNode&&this.clickedNode.id||this.root);this.controller.onBeforeCompute(b);var c=this.config,d=this.canvas.getSize(),e=d.width,d=d.height,f=c.offset,h=e-f,f=d-f;this.graph.computeLevels(this.root,0,"ignore");b.getPos(a).setc(-e/2,-d/2);b.setData("width",e,a);b.setData("height",d,a);this.computePositions(b,{top:-d/2+c.titleHeight,left:-e/2,width:h,
height:f-c.titleHeight},a);this.controller.onAfterCompute(b)},computeDim:function(a,b,c,d,e,f){if(1==a.length+b.length)this.layoutLast(1==a.length?a:b,c,d,f);else if(2<=a.length&&0==b.length&&(b=[a.shift()]),0==a.length)0<b.length&&this.layoutRow(b,c,d,f);else{var h=a[0];e(b,c)>=e([h].concat(b),c)?this.computeDim(a.slice(1),b.concat([h]),c,d,e,f):(b=this.layoutRow(b,c,d,f),this.computeDim(a,[],b.dim,b,e,f))}},worstAspectRatio:function(a,b){if(!a||0==a.length)return Number.MAX_VALUE;for(var c=0,d=
0,e=Number.MAX_VALUE,f=0,h=a.length;f<h;f++)var g=a[f]._area,c=c+g,e=e<g?e:g,d=d>g?d:g;f=b*b;c*=c;return Math.max(f*d/c,c/(f*e))},avgAspectRatio:function(a,b){if(!a||0==a.length)return Number.MAX_VALUE;for(var c=0,d=0,e=a.length;d<e;d++)var f=a[d]._area/b,c=c+(b>f?b/f:f/b);return c/e},layoutLast:function(a,b,c,d){a=a[0];a.getPos(d).setc(c.left,c.top);a.setData("width",c.width,d);a.setData("height",c.height,d)}};n.TM.Squarified=new i({Implements:n.TM.Area,computePositions:function(a,b,c){var d=this.config,
e=Math.max;this.layout.orientation=b.width>=b.height?"h":"v";var f=a.getSubnodes([1,1],"ignore");if(0<f.length){this.processChildrenLayout(a,f,b,c);for(var a=0,h=f.length;a<h;a++){var g=f[a],k=d.offset,b=e(g.getData("height",c)-k-d.titleHeight,0),k=e(g.getData("width",c)-k,0),m=g.getPos(c),b={width:k,height:b,top:m.y+d.titleHeight,left:m.x};this.computePositions(g,b,c)}}},processChildrenLayout:function(a,b,c,d){var a=c.width*c.height,e,f=b.length,g=0,j=[];for(e=0;e<f;e++)j[e]=parseFloat(b[e].getData("area",
d)),g+=j[e];for(e=0;e<f;e++)b[e]._area=a*j[e]/g;a=this.layout.horizontal()?c.height:c.width;b.sort(function(a,b){var c=b._area-a._area;return c?c:b.id==a.id?0:b.id<a.id?1:-1});e=[b[0]];b=b.slice(1);this.squarify(b,e,a,c,d)},squarify:function(a,b,c,d,e){this.computeDim(a,b,c,d,this.worstAspectRatio,e)},layoutRow:function(a,b,c,d){return this.layout.horizontal()?this.layoutV(a,b,c,d):this.layoutH(a,b,c,d)},layoutV:function(a,b,c,d){var e=0;g.each(a,function(a){e+=a._area});for(var b=e/b,f=0,h=0,j=a.length;h<
j;h++){var k=a[h]._area/b,m=a[h];m.getPos(d).setc(c.left,c.top+f);m.setData("width",b,d);m.setData("height",k,d);f+=k}a={height:c.height,width:c.width-b,top:c.top,left:c.left+b};a.dim=Math.min(a.width,a.height);a.dim!=a.height&&this.layout.change();return a},layoutH:function(a,b,c,d){var e=0;g.each(a,function(a){e+=a._area});for(var f=e/b,h=c.top,j=0,k=0,m=a.length;k<m;k++){var i=a[k],b=i._area/f;i.getPos(d).setc(c.left+j,h);i.setData("width",b,d);i.setData("height",f,d);j+=b}a={height:c.height-f,
width:c.width,top:c.top+f,left:c.left};a.dim=Math.min(a.width,a.height);a.dim!=a.width&&this.layout.change();return a}});n.TM.Strip=new i({Implements:n.TM.Area,computePositions:function(a,b,c){var d=a.getSubnodes([1,1],"ignore"),e=this.config,f=Math.max;if(0<d.length){this.processChildrenLayout(a,d,b,c);for(var a=0,g=d.length;a<g;a++){var j=d[a],k=e.offset,b=f(j.getData("height",c)-k-e.titleHeight,0),k=f(j.getData("width",c)-k,0),m=j.getPos(c),b={width:k,height:b,top:m.y+e.titleHeight,left:m.x};this.computePositions(j,
b,c)}}},processChildrenLayout:function(a,b,c,d){var a=c.width*c.height,e,f=b.length,g=0,j=[];for(e=0;e<f;e++)j[e]=+b[e].getData("area",d),g+=j[e];for(e=0;e<f;e++)b[e]._area=a*j[e]/g;a=this.layout.horizontal()?c.width:c.height;e=[b[0]];b=b.slice(1);this.stripify(b,e,a,c,d)},stripify:function(a,b,c,d,e){this.computeDim(a,b,c,d,this.avgAspectRatio,e)},layoutRow:function(a,b,c,d){return this.layout.horizontal()?this.layoutH(a,b,c,d):this.layoutV(a,b,c,d)},layoutV:function(a,b,c,d){var e=0;g.each(a,function(a){e+=
a._area});for(var f=e/b,h=0,j=0,k=a.length;j<k;j++){var m=a[j],i=m._area/f;m.getPos(d).setc(c.left,c.top+(b-i-h));m.setData("width",f,d);m.setData("height",i,d);h+=i}return{height:c.height,width:c.width-f,top:c.top,left:c.left+f,dim:b}},layoutH:function(a,b,c,d){var e=0;g.each(a,function(a){e+=a._area});for(var f=e/b,h=c.height-f,j=0,k=0,m=a.length;k<m;k++){var i=a[k],l=i._area/f;i.getPos(d).setc(c.left+j,c.top+h);i.setData("width",l,d);i.setData("height",f,d);j+=l}return{height:c.height-f,width:c.width,
top:c.top,left:c.left,dim:b}}});n.Icicle=new i({compute:function(a){var a=a||"current",b=this.graph.getNode(this.root),c=this.config,d=this.canvas.getSize(),e=d.width,d=d.height,c=c.constrained?c.levelsToShow:Number.MAX_VALUE;this.controller.onBeforeCompute(b);l.Util.computeLevels(this.graph,b.id,0,"ignore");var f=0;l.Util.eachLevel(b,0,!1,function(a,b){b>f&&(f=b)});var b=this.graph.getNode(this.clickedNode&&this.clickedNode.id||b.id),c=Math.min(f,c-1),g=b._depth;this.layout.horizontal()?this.computeSubtree(b,
-e/2,-d/2,e/(c+1),d,g,c,a):this.computeSubtree(b,-e/2,-d/2,e,d/(c+1),g,c,a)},computeSubtree:function(a,b,c,d,e,f,h,j){a.getPos(j).setc(b,c);a.setData("width",d,j);a.setData("height",e,j);var k=0,m=l.Util.getSubnodes(a,[1,1],"ignore");if(m.length){g.each(m,function(a){k+=a.getData("dim")});for(var i=0,n=m.length;i<n;i++)this.layout.horizontal()?(a=e*m[i].getData("dim")/k,this.computeSubtree(m[i],b+d,c,d,a,f,h,j),c+=a):(a=d*m[i].getData("dim")/k,this.computeSubtree(m[i],b,c+e,a,e,f,h,j),b+=a)}}});$jit.Icicle=
new i({Implements:[s,A,n.Icicle],layout:{orientation:"h",vertical:function(){return"v"==this.orientation},horizontal:function(){return"h"==this.orientation},change:function(){this.orientation=this.vertical()?"h":"v"}},initialize:function(a){var b={animate:!1,orientation:"h",offset:2,levelsToShow:Number.MAX_VALUE,constrained:!1,Node:{type:"rectangle",overridable:!0},Edge:{type:"none"},Label:{type:"Native"},duration:700,fps:45},c=r("Canvas","Node","Edge","Fx","Tips","NodeStyles","Events","Navigation",
"Controller","Label");this.controller=this.config=g.merge(c,b,a);this.layout.orientation=this.config.orientation;a=this.config;a.useCanvas?(this.canvas=a.useCanvas,this.config.labelContainer=this.canvas.id+"-label"):(this.canvas=new u(this,a),this.config.labelContainer=("string"==typeof a.injectInto?a.injectInto:a.injectInto.id)+"-label");this.graphOptions={klass:o,Node:{selected:!1,exist:!0,drawn:!0}};this.graph=new l(this.graphOptions,this.config.Node,this.config.Edge,this.config.Label);this.labels=
new $jit.Icicle.Label[this.config.Label.type](this);this.fx=new $jit.Icicle.Plot(this,$jit.Icicle);this.op=new $jit.Icicle.Op(this);this.group=new $jit.Icicle.Group(this);this.clickedNode=null;this.initializeExtras()},refresh:function(){if("Native"!=this.config.Label.type){var a=this;this.graph.eachNode(function(b){a.labels.hideLabel(b,!1)})}this.compute();this.plot()},plot:function(){this.fx.plot(this.config)},enter:function(a){if(!this.busy){this.busy=!0;var b=this,c=this.config,d={onComplete:function(){c.request&&
b.compute();c.animate?(b.graph.nodeList.setDataset(["current","end"],{alpha:[1,0]}),l.Util.eachSubgraph(a,function(a){a.setData("alpha",1,"end")},"ignore"),b.fx.animate({duration:500,modes:["node-property:alpha"],onComplete:function(){b.clickedNode=a;b.compute("end");b.fx.animate({modes:["linear","node-property:width:height"],duration:1E3,onComplete:function(){b.busy=!1;b.clickedNode=a}})}})):(b.clickedNode=a,b.busy=!1,b.refresh())}};if(c.request)this.requestNodes(clickedNode,d);else d.onComplete()}},
out:function(){if(!this.busy){var a=this,b=l.Util,c=this.config,d=this.graph,e=b.getParents(d.getNode(this.clickedNode&&this.clickedNode.id||this.root))[0],f=this.clickedNode;this.busy=!0;this.events.hoveredNode=!1;if(e)if(callback={onComplete:function(){a.clickedNode=e;c.request?a.requestNodes(e,{onComplete:function(){a.compute();a.plot();a.busy=!1}}):(a.compute(),a.plot(),a.busy=!1)}},c.animate)this.clickedNode=e,this.compute("end"),this.clickedNode=f,this.fx.animate({modes:["linear","node-property:width:height"],
duration:1E3,onComplete:function(){a.clickedNode=e;d.nodeList.setDataset(["current","end"],{alpha:[0,1]});b.eachSubgraph(f,function(a){a.setData("alpha",1)},"ignore");a.fx.animate({duration:500,modes:["node-property:alpha"],onComplete:function(){callback.onComplete()}})}});else callback.onComplete();else this.busy=!1}},requestNodes:function(a,b){var c=g.merge(this.controller,b),d=this.config.constrained?this.config.levelsToShow:Number.MAX_VALUE;if(c.request){var e=[],f=a._depth;l.Util.eachLevel(a,
0,d,function(a){a.drawn&&!l.Util.anySubnode(a)&&(e.push(a),a._level=a._depth-f,this.config.constrained&&(a._level=d-a._level))});this.group.requestNodes(e,c)}else c.onComplete()}});$jit.Icicle.Op=new i({Implements:l.Op});$jit.Icicle.Group=new i({initialize:function(a){this.viz=a;this.canvas=a.canvas;this.config=a.config},requestNodes:function(a,b){var c=0,d=a.length,e=this.viz;if(0==d)b.onComplete();for(var f=0;f<d;f++)b.request(a[f].id,a[f]._level,{onComplete:function(a,f){f&&f.children&&(f.id=a,
e.op.sum(f,{type:"nothing"}));++c==d&&(l.Util.computeLevels(e.graph,e.root,0),b.onComplete())}})}});$jit.Icicle.Plot=new i({Implements:l.Plot,plot:function(a,b){var a=a||this.viz.controller,c=this.viz,d=c.graph.getNode(c.clickedNode&&c.clickedNode.id||c.root),e=d._depth;c.canvas.clear();this.plotTree(d,g.merge(a,{withLabels:!0,hideLabels:!1,plotSubtree:function(a,b){return!c.config.constrained||b._depth-e<c.config.levelsToShow}}),b)}});$jit.Icicle.Label={};$jit.Icicle.Label.Native=new i({Implements:l.Label.Native,
renderLabel:function(a,b){var c=a.getCtx(),d=b.getData("width"),e=b.getData("height"),f=b.getLabelData("size"),g=c.measureText(b.name);e<1.5*f||d<g.width||(f=b.pos.getc(!0),c.fillText(b.name,f.x+d/2,f.y+e/2))}});$jit.Icicle.Label.SVG=new i({Implements:l.Label.SVG,initialize:function(a){this.viz=a},placeLabel:function(a,b,c){var d=b.pos.getc(!0),e=this.viz.canvas.getSize(),f=Math.round(d.x+e.width/2),d=Math.round(d.y+e.height/2);a.setAttribute("x",f);a.setAttribute("y",d);c.onPlaceLabel(a,b)}});$jit.Icicle.Label.HTML=
new i({Implements:l.Label.HTML,initialize:function(a){this.viz=a},placeLabel:function(a,b,c){var d=b.pos.getc(!0),e=this.viz.canvas.getSize(),f=Math.round(d.x+e.width/2),d=Math.round(d.y+e.height/2),e=a.style;e.left=f+"px";e.top=d+"px";e.display="";c.onPlaceLabel(a,b)}});$jit.Icicle.Plot.NodeTypes=new i({none:{render:g.empty},rectangle:{render:function(a,b){var c=this.viz.config,d=c.offset,e=a.getData("width"),f=a.getData("height"),h=a.getData("border"),j=a.pos.getc(!0),k=j.x+d/2,i=j.y+d/2,l=b.getCtx();
if(!(2>e-d||2>f-d)){if(c.cushion){var c=a.getData("color"),n=l.createRadialGradient(k+(e-d)/2,i+(f-d)/2,1,k+(e-d)/2,i+(f-d)/2,e<f?f:e),w=g.rgbToHex(g.map(g.hexToRgb(c),function(a){return 0.3*a>>0}));n.addColorStop(0,c);n.addColorStop(1,w);l.fillStyle=n}h&&(l.strokeStyle=h,l.lineWidth=3);l.fillRect(k,i,Math.max(0,e-d),Math.max(0,f-d));h&&l.strokeRect(j.x,j.y,e,f)}},contains:function(a,b){if(this.viz.clickedNode&&!$jit.Graph.Util.isDescendantOf(a,this.viz.clickedNode.id))return!1;var c=a.pos.getc(!0),
d=a.getData("width"),e=a.getData("height");return this.nodeHelper.rectangle.contains({x:c.x+d/2,y:c.y+e/2},b,d,e)}}});$jit.Icicle.Plot.EdgeTypes=new i({none:g.empty});n.Radial=new i({compute:function(a){a=g.splat(a||["current","start","end"]);T.compute(this.graph,a,this.config);this.graph.computeLevels(this.root,0,"ignore");var b=this.createLevelDistanceFunc();this.computeAngularWidths(a);this.computePositions(a,b)},computePositions:function(a,b){for(var c=this.graph,d=c.getNode(this.root),e=this.parent,
f=0,g=a.length;f<g;f++){var j=a[f];d.setPos(new p(0,0),j);d.setData("span",2*Math.PI,j)}d.angleSpan={begin:0,end:2*Math.PI};c.eachBFS(this.root,function(c){var d=c.angleSpan.end-c.angleSpan.begin,f=c.angleSpan.begin,g=b(c),h=0,j=[],i={};c.eachSubnode(function(b){h+=b._treeAngularWidth;for(var c=0,d=a.length;c<d;c++){var e=a[c],f=b.getData("dim",e);i[e]=e in i?f>i[e]?f:i[e]:f}j.push(b)},"ignore");e&&(e.id==c.id&&0<j.length&&j[0].dist)&&j.sort(function(a,b){return(a.dist>=b.dist)-(a.dist<=b.dist)});
for(var c=0,l=j.length;c<l;c++){var n=j[c];if(!n._flag){for(var o=n._treeAngularWidth/h*d,r=f+o/2,s=0,v=a.length;s<v;s++){var u=a[s];n.setPos(new p(r,g),u);n.setData("span",o,u);n.setData("dim-quotient",n.getData("dim",u)/i[u],u)}n.angleSpan={begin:f,end:f+o};f+=o}}},"ignore")},setAngularWidthForNodes:function(a){this.graph.eachBFS(this.root,function(b,c){var d=b.getData("angularWidth",a[0])||5;b._angularWidth=d/c},"ignore")},setSubtreesAngularWidth:function(){var a=this;this.graph.eachNode(function(b){a.setSubtreeAngularWidth(b)},
"ignore")},setSubtreeAngularWidth:function(a){var b=this,c=a._angularWidth,d=0;a.eachSubnode(function(a){b.setSubtreeAngularWidth(a);d+=a._treeAngularWidth},"ignore");a._treeAngularWidth=Math.max(c,d)},computeAngularWidths:function(a){this.setAngularWidthForNodes(a);this.setSubtreesAngularWidth()}});$jit.RGraph=new i({Implements:[s,A,n.Radial],initialize:function(a){var b=$jit.RGraph,a=this.controller=this.config=g.merge(r("Canvas","Node","Edge","Fx","Controller","Tips","NodeStyles","Events","Navigation",
"Label"),{interpolation:"linear",levelDistance:100},a);a.useCanvas?(this.canvas=a.useCanvas,this.config.labelContainer=this.canvas.id+"-label"):(a.background&&(a.background=g.merge({type:"Circles"},a.background)),this.canvas=new u(this,a),this.config.labelContainer=("string"==typeof a.injectInto?a.injectInto:a.injectInto.id)+"-label");this.graphOptions={klass:p,Node:{selected:!1,exist:!0,drawn:!0}};this.graph=new l(this.graphOptions,this.config.Node,this.config.Edge);this.labels=new b.Label[a.Label.type](this);
this.fx=new b.Plot(this,b);this.op=new b.Op(this);this.root=this.json=null;this.parent=this.busy=!1;this.initializeExtras()},createLevelDistanceFunc:function(){var a=this.config.levelDistance;return function(b){return(b._depth+1)*a}},refresh:function(){this.compute();this.plot()},reposition:function(){this.compute("end")},plot:function(){this.fx.plot()},getNodeAndParentAngle:function(a){var b=!1,c=this.graph.getNode(a),a=c.getParents();if(a=0<a.length?a[0]:!1)b=a.pos.getc(),c=c.pos.getc(),b=b.add(c.scale(-1)),
b=Math.atan2(b.y,b.x),0>b&&(b+=2*Math.PI);return{parent:a,theta:b}},tagChildren:function(a,b){if(a.angleSpan){var c=[];a.eachAdjacency(function(a){c.push(a.nodeTo)},"ignore");for(var d=c.length,e=0;e<d&&b!=c[e].id;e++);for(var e=(e+1)%d,f=0;b!=c[e].id;e=(e+1)%d)c[e].dist=f++}},onClick:function(a,b){if(this.root!=a&&!this.busy){this.busy=!0;this.root=a;var c=this;this.controller.onBeforeCompute(this.graph.getNode(a));var d=this.getNodeAndParentAngle(a);this.tagChildren(d.parent,a);this.parent=d.parent;
this.compute("end");var e=d.theta-d.parent.endPos.theta;this.graph.eachNode(function(a){a.endPos.set(a.endPos.getp().add(new p(e,0)))});d=this.config.interpolation;b=g.merge({onComplete:g.empty},b||{});this.fx.animate(g.merge({hideLabels:!0,modes:[d]},b,{onComplete:function(){c.busy=!1;b.onComplete()}}))}}});$jit.RGraph.$extend=!0;var v=$jit.RGraph;v.Op=new i({Implements:l.Op});v.Plot=new i({Implements:l.Plot});v.Label={};v.Label.Native=new i({Implements:l.Label.Native});v.Label.SVG=new i({Implements:l.Label.SVG,
initialize:function(a){this.viz=a},placeLabel:function(a,b,c){var d=b.pos.getc(!0),e=this.viz.canvas,f=e.translateOffsetX,g=e.translateOffsetY,j=e.scaleOffsetX,k=e.scaleOffsetY,e=e.getSize(),f=Math.round(d.x*j+f+e.width/2),d=Math.round(d.y*k+g+e.height/2);a.setAttribute("x",f);a.setAttribute("y",d);c.onPlaceLabel(a,b)}});v.Label.HTML=new i({Implements:l.Label.HTML,initialize:function(a){this.viz=a},placeLabel:function(a,b,c){var d=b.pos.getc(!0),e=this.viz.canvas,f=e.translateOffsetX,g=e.translateOffsetY,
j=e.scaleOffsetX,k=e.scaleOffsetY,i=e.getSize(),d={x:Math.round(d.x*j+f+i.width/2),y:Math.round(d.y*k+g+i.height/2)},f=a.style;f.left=d.x+"px";f.top=d.y+"px";f.display=this.fitsInCanvas(d,e)?"":"none";c.onPlaceLabel(a,b)}});v.Plot.NodeTypes=new i({none:{render:g.empty,contains:g.lambda(!1)},circle:{render:function(a,b){var c=a.pos.getc(!0),d=a.getData("dim");this.nodeHelper.circle.render("fill",c,d,b)},contains:function(a,b){var c=a.pos.getc(!0),d=a.getData("dim");return this.nodeHelper.circle.contains(c,
b,d)}},ellipse:{render:function(a,b){var c=a.pos.getc(!0),d=a.getData("width"),e=a.getData("height");this.nodeHelper.ellipse.render("fill",c,d,e,b)},contains:function(a,b){var c=a.pos.getc(!0),d=a.getData("width"),e=a.getData("height");return this.nodeHelper.ellipse.contains(c,b,d,e)}},square:{render:function(a,b){var c=a.pos.getc(!0),d=a.getData("dim");this.nodeHelper.square.render("fill",c,d,b)},contains:function(a,b){var c=a.pos.getc(!0),d=a.getData("dim");return this.nodeHelper.square.contains(c,
b,d)}},rectangle:{render:function(a,b){var c=a.pos.getc(!0),d=a.getData("width"),e=a.getData("height");this.nodeHelper.rectangle.render("fill",c,d,e,b)},contains:function(a,b){var c=a.pos.getc(!0),d=a.getData("width"),e=a.getData("height");return this.nodeHelper.rectangle.contains(c,b,d,e)}},triangle:{render:function(a,b){var c=a.pos.getc(!0),d=a.getData("dim");this.nodeHelper.triangle.render("fill",c,d,b)},contains:function(a,b){var c=a.pos.getc(!0),d=a.getData("dim");return this.nodeHelper.triangle.contains(c,
b,d)}},star:{render:function(a,b){var c=a.pos.getc(!0),d=a.getData("dim");this.nodeHelper.star.render("fill",c,d,b)},contains:function(a,b){var c=a.pos.getc(!0),d=a.getData("dim");return this.nodeHelper.star.contains(c,b,d)}}});v.Plot.EdgeTypes=new i({none:g.empty,line:{render:function(a,b){var c=a.nodeFrom.pos.getc(!0),d=a.nodeTo.pos.getc(!0);this.edgeHelper.line.render(c,d,b)},contains:function(a,b){var c=a.nodeFrom.pos.getc(!0),d=a.nodeTo.pos.getc(!0);return this.edgeHelper.line.contains(c,d,b,
this.edge.epsilon)}},arrow:{render:function(a,b){var c=a.nodeFrom.pos.getc(!0),d=a.nodeTo.pos.getc(!0),e=a.getData("dim"),f=a.data.$direction;this.edgeHelper.arrow.render(c,d,e,f&&1<f.length&&f[0]!=a.nodeFrom.id,b)},contains:function(a,b){var c=a.nodeFrom.pos.getc(!0),d=a.nodeTo.pos.getc(!0);return this.edgeHelper.arrow.contains(c,d,b,this.edge.epsilon)}}});l.Geom=new i({initialize:function(a){this.viz=a;this.config=a.config;this.node=a.config.Node;this.edge=a.config.Edge},translate:function(a,b){b=
g.splat(b);this.viz.graph.eachNode(function(c){g.each(b,function(b){c.getPos(b).$add(a)})})},setRightLevelToShow:function(a,b,c){var d=this.getRightLevelToShow(a,b),e=this.viz.labels,f=g.merge({execShow:!0,execHide:!0,onHide:g.empty,onShow:g.empty},c||{});a.eachLevel(0,this.config.levelsToShow,function(b){b._depth-a._depth>d?(f.onHide(b),f.execHide&&(b.drawn=!1,b.exist=!1,e.hideLabel(b,!1))):(f.onShow(b),f.execShow&&(b.exist=!0))});a.drawn=!0},getRightLevelToShow:function(a,b){var c=this.config,d=
c.levelsToShow;if(!c.constrained)return d;for(;!this.treeFitsInCanvas(a,b,d)&&1<d;)d--;return d}});var O=function(a,b){var c=[];g.each(a,function(a){a=U.call(a);a[0]+=b;a[1]+=b;c.push(a)});return c},I=function(a,b){if(0==a.length)return b;if(0==b.length)return a;var c=a.shift(),d=b.shift();return[[c[0],d[1]]].concat(I(a,b))},V=function(a,b){b=b||[];if(0==a.length)return b;var c=a.pop();return V(a,I(c,b))},P=function(a,b,c,d,e){if(a.length<=e||b.length<=e)return 0;var f=a[e][1],g=b[e][0];return Math.max(P(a,
b,c,d,++e)+c,f-g+d)},U=Array.prototype.slice,v=new i({compute:function(a,b){var c=a||"start",d=this.graph.getNode(this.root);g.extend(d,{drawn:!0,exist:!0,selected:!0});T.compute(this.graph,c,this.config);(b||!("_depth"in d))&&this.graph.computeLevels(this.root,0,"ignore");this.computePositions(d,c)},computePositions:function(a,b){var c=this.config,d=c.multitree,e=c.align,f="center"!==e&&c.indent,c=c.orientation,h=this;g.each(d?["top","right","bottom","left"]:[c],function(c){var g=h.graph,i=h.config,
l=function(a,d,e){var f=a.getData(u,b),h=[],o=[],p=!1,r=(d||a.getData(v,b))+i.levelDistance;a.eachSubnode(function(a){if(a.exist&&(!n||"$orn"in a.data&&a.data.$orn==c)){if(!p){var d=a._depth,f=i.Node,w=i.multitree;if(f.overridable){var q=-1,s=-1;g.eachNode(function(a){if(a._depth==d&&(!w||"$orn"in a.data&&a.data.$orn==c)){var e=a.getData("width",b),a=a.getData("height",b);q=q<e?e:q;s=s<a?a:s}});p={width:0>q?f.width:q,height:0>s?f.height:s}}else p=f}a=l(a,p[v],e+r);h.push(a.tree);o.push(a.extent)}});
var w=C,y=A,d=E,x,z=function(a,b,c){if(b.length<=c)return[];var d=b[c],e=P(a,d,w,y,0);return[e].concat(z(I(a,O(d,e)),b,++c))};x=z([],o,0);var B,F=function(a,b,c){if(b.length<=c)return[];var d=b[c],e=-P(d,a,w,y,0);return[e].concat(F(I(O(d,e),a),b,++c))};B=U.call(o);B=F([],B.reverse(),0).reverse();"left"==d?B=x:"right"==d&&(x=B);for(var D=0,d=[];D<x.length;D++)d[D]=(x[D]+B[D])/2;x=0;for(B=[];x<h.length;x++){var D=d[x],H="left"==c||"right"==c?"y":"x";h[x].getPos(b)[H]+=D;B.push(O(o[x],d[x]))}f=[[-f/
2,f/2]].concat(V(B));a.getPos(b)[q]=0;"top"==c||"left"==c?a.getPos(b)[s]=e:a.getPos(b)[s]=-e;return{tree:a,extent:f}},n=i.multitree,o=["x","y"],p=["width","height"],r=+("left"==c||"right"==c),q=o[r],s=o[1-r],u=p[r],v=p[1-r],A=i.siblingOffset,C=i.subtreeOffset,E=i.align;l(a,!1,0);var y=["x","y"][+("left"==c||"right"==c)];(function Z(a){a.eachSubnode(function(g){if(g.exist&&(!d||"$orn"in g.data&&g.data.$orn==c))g.getPos(b)[y]+=a.getPos(b)[y],f&&(g.getPos(b)[y]+="left"==e?f:-f),Z(g)})})(a)})}});n.Tree=
v;var v=$jit,W=function(a){a=a||this.clickedNode;if(!this.config.constrained)return[];var b=this.geom,c=this.canvas,d=a._depth,e=[];this.graph.eachNode(function(b){b.exist&&!b.selected&&(b.isDescendantOf(a.id)?b._depth<=d&&e.push(b):e.push(b))});b=b.getRightLevelToShow(a,c);a.eachLevel(b,b,function(a){a.exist&&!a.selected&&e.push(a)});for(b=0;b<E.length;b++)c=this.graph.getNode(E[b]),c.isDescendantOf(a.id)||e.push(c);return e},X=function(){var a=[],b=this.config;this.clickedNode.eachLevel(0,b.levelsToShow,
function(c){b.multitree&&!("$orn"in c.data)&&c.anySubnode(function(a){return a.exist&&!a.drawn})?a.push(c):c.drawn&&!c.anySubnode("drawn")&&a.push(c)});return a},E=[],s=new i({Implements:[s,A,n.Tree],initialize:function(a){var b=$jit.ST,a=this.controller=this.config=g.merge(r("Canvas","Fx","Tree","Node","Edge","Controller","Tips","NodeStyles","Events","Navigation","Label"),{levelsToShow:2,levelDistance:30,constrained:!0,Node:{type:"rectangle"},duration:700,offsetX:0,offsetY:0},a);a.useCanvas?(this.canvas=
a.useCanvas,this.config.labelContainer=this.canvas.id+"-label"):(a.background&&(a.background=g.merge({type:"Circles"},a.background)),this.canvas=new u(this,a),this.config.labelContainer=("string"==typeof a.injectInto?a.injectInto:a.injectInto.id)+"-label");this.graphOptions={klass:o};this.graph=new l(this.graphOptions,this.config.Node,this.config.Edge);this.labels=new b.Label[a.Label.type](this);this.fx=new b.Plot(this,b);this.op=new b.Op(this);this.group=new b.Group(this);this.geom=new b.Geom(this);
this.clickedNode=null;this.initializeExtras()},plot:function(){this.fx.plot(this.controller)},switchPosition:function(a,b,c){var d=this.geom,e=this.fx,f=this;e.busy||(e.busy=!0,this.contract({onComplete:function(){d.switchOrientation(a);f.compute("end",!1);e.busy=!1;if("animate"==b)f.onClick(f.clickedNode.id,c);else"replot"==b&&f.select(f.clickedNode.id,c)}},a))},switchAlignment:function(a,b,c){this.config.align=a;if("animate"==b)this.select(this.clickedNode.id,c);else if("replot"==b)this.onClick(this.clickedNode.id,
c)},addNodeInPath:function(a){E.push(a);this.select(this.clickedNode&&this.clickedNode.id||this.root)},clearNodesInPath:function(){E.length=0;this.select(this.clickedNode&&this.clickedNode.id||this.root)},refresh:function(){this.reposition();this.select(this.clickedNode&&this.clickedNode.id||this.root)},reposition:function(){this.graph.computeLevels(this.root,0,"ignore");this.geom.setRightLevelToShow(this.clickedNode,this.canvas);this.graph.eachNode(function(a){a.exist&&(a.drawn=!0)});this.compute("end")},
requestNodes:function(a,b){var c=g.merge(this.controller,b),d=this.config.levelsToShow;if(c.request){var e=[],f=a._depth;a.eachLevel(0,d,function(a){a.drawn&&!a.anySubnode()&&(e.push(a),a._level=d-(a._depth-f))});this.group.requestNodes(e,c)}else c.onComplete()},contract:function(a,b){var c=this.config.orientation,d=this.geom,e=this.group;b&&d.switchOrientation(b);var f=W.call(this);b&&d.switchOrientation(c);e.contract(f,g.merge(this.controller,a))},move:function(a,b){this.compute("end",!1);var c=
b.Move,d={x:c.offsetX,y:c.offsetY};c.enable&&this.geom.translate(a.endPos.add(d).$scale(-1),"end");this.fx.animate(g.merge(this.controller,{modes:["linear"]},b))},expand:function(a,b){var c=X.call(this,a);this.group.expand(c,g.merge(this.controller,b))},selectPath:function(a){function b(a){null==a||a.selected||(a.selected=!0,g.each(c.group.getSiblings([a])[a.id],function(a){a.exist=!0;a.drawn=!0}),a=a.getParents(),a=0<a.length?a[0]:null,b(a))}var c=this;this.graph.eachNode(function(a){a.selected=
!1});for(var d=0,a=[a.id].concat(E);d<a.length;d++)b(this.graph.getNode(a[d]))},setRoot:function(a,b,c){function d(){if(this.config.multitree&&j.data.$orn){var b={left:"right",right:"left",top:"bottom",bottom:"top"}[j.data.$orn];g.data.$orn=b;(function t(c){c.eachSubnode(function(c){c.id!=a&&(c.data.$orn=b,t(c))})})(g);delete j.data.$orn}this.root=a;this.clickedNode=j;this.graph.computeLevels(this.root,0,"ignore");this.geom.setRightLevelToShow(j,f,{execHide:!1,onShow:function(a){a.drawn||(a.drawn=
!0,a.setData("alpha",1,"end"),a.setData("alpha",0),a.pos.setc(j.pos.x,j.pos.y))}});this.compute("end");this.busy=!0;this.fx.animate({modes:["linear","node-property:alpha"],onComplete:function(){e.busy=!1;e.onClick(a,{onComplete:function(){c&&c.onComplete()}})}})}if(!this.busy){this.busy=!0;var e=this,f=this.canvas,g=this.graph.getNode(this.root),j=this.graph.getNode(a);delete g.data.$orns;"animate"==b?(d.call(this),e.selectPath(j)):"replot"==b&&(d.call(this),this.select(this.root))}},addSubtree:function(a,
b,c){"replot"==b?this.op.sum(a,g.extend({type:"replot"},c||{})):"animate"==b&&this.op.sum(a,g.extend({type:"fade:seq"},c||{}))},removeSubtree:function(a,b,c,d){var e=[];this.graph.getNode(a).eachLevel(+!b,!1,function(a){e.push(a.id)});"replot"==c?this.op.removeNode(e,g.extend({type:"replot"},d||{})):"animate"==c&&this.op.removeNode(e,g.extend({type:"fade:seq"},d||{}))},select:function(a,b){var c=this.group,d=this.geom,e=this.graph.getNode(a),f=this.canvas;this.graph.getNode(this.root);var h=g.merge(this.controller,
b),j=this;h.onBeforeCompute(e);this.selectPath(e);this.clickedNode=e;this.requestNodes(e,{onComplete:function(){c.hide(c.prepare(W.call(j)),h);d.setRightLevelToShow(e,f);j.compute("current");j.graph.eachNode(function(a){var b=a.pos.getc(!0);a.startPos.setc(b.x,b.y);a.endPos.setc(b.x,b.y);a.visited=!1});j.geom.translate(e.endPos.add({x:h.offsetX,y:h.offsetY}).$scale(-1),["start","current","end"]);c.show(X.call(j));j.plot();h.onAfterCompute(j.clickedNode);h.onComplete()}})},onClick:function(a,b){var c=
this.canvas,d=this,e=this.geom,f=this.config,h=g.merge(this.controller,{Move:{enable:!0,offsetX:f.offsetX||0,offsetY:f.offsetY||0},setRightLevelToShowConfig:!1,onBeforeRequest:g.empty,onBeforeContract:g.empty,onBeforeMove:g.empty,onBeforeExpand:g.empty},b);if(!this.busy){this.busy=!0;var j=this.graph.getNode(a);this.selectPath(j,this.clickedNode);this.clickedNode=j;h.onBeforeCompute(j);h.onBeforeRequest(j);this.requestNodes(j,{onComplete:function(){h.onBeforeContract(j);d.contract({onComplete:function(){e.setRightLevelToShow(j,
c,h.setRightLevelToShowConfig);h.onBeforeMove(j);d.move(j,{Move:h.Move,onComplete:function(){h.onBeforeExpand(j);d.expand(j,{onComplete:function(){d.busy=!1;h.onAfterCompute(a);h.onComplete()}})}})}})}})}}});v.ST=s;$jit.ST.$extend=!0;$jit.ST.Op=new i({Implements:l.Op});$jit.ST.Group=new i({initialize:function(a){this.viz=a;this.canvas=a.canvas;this.config=a.config;this.animation=new F;this.nodes=null},requestNodes:function(a,b){var c=0,d=a.length,e=this.viz;if(0==d)b.onComplete();for(var f=0;f<d;f++)b.request(a[f].id,
a[f]._level,{onComplete:function(a,f){f&&f.children&&(f.id=a,e.op.sum(f,{type:"nothing"}));++c==d&&(e.graph.computeLevels(e.root,0),b.onComplete())}})},contract:function(a,b){var c=this,a=this.prepare(a);this.animation.setOptions(g.merge(b,{$animating:!1,compute:function(a){1==a&&(a=0.99);c.plotStep(1-a,b,this.$animating);this.$animating="contract"},complete:function(){c.hide(a,b)}})).start()},hide:function(a,b){for(var c=0;c<a.length;c++)a[c].eachLevel(1,!1,function(a){a.exist&&g.extend(a,{drawn:false,
exist:false})});b.onComplete()},expand:function(a,b){var c=this;this.show(a);this.animation.setOptions(g.merge(b,{$animating:!1,compute:function(a){c.plotStep(a,b,this.$animating);this.$animating="expand"},complete:function(){c.plotStep(void 0,b,!1);b.onComplete()}})).start()},show:function(a){var b=this.config;this.prepare(a);g.each(a,function(a){if(b.multitree&&!("$orn"in a.data)){delete a.data.$orns;var d=" ";a.eachSubnode(function(a){"$orn"in a.data&&(0>d.indexOf(a.data.$orn)&&a.exist&&!a.drawn)&&
(d+=a.data.$orn+" ")});a.data.$orns=d}a.eachLevel(0,b.levelsToShow,function(a){a.exist&&(a.drawn=!0)})})},prepare:function(a){return this.nodes=this.getNodesWithChildren(a)},getNodesWithChildren:function(a){var b=[],c=this.config;a.sort(function(a,b){return(a._depth<=b._depth)-(a._depth>=b._depth)});for(var d=0;d<a.length;d++)if(a[d].anySubnode("exist")){for(var e=d+1,f=!1;!f&&e<a.length;e++)if(!c.multitree||"$orn"in a[e].data)f=f||a[d].isDescendantOf(a[e].id);f||b.push(a[d])}return b},plotStep:function(a,
b,c){var d=this.viz,e=this.config,f=d.canvas.getCtx(),h=this.nodes,j,i,m={};for(j=0;j<h.length;j++){i=h[j];m[i.id]=[];var l=e.multitree&&!("$orn"in i.data),n=l&&i.data.$orns;i.eachSubgraph(function(a){if(l&&n&&0<n.indexOf(a.data.$orn)&&a.drawn)a.drawn=!1,m[i.id].push(a);else if((!l||!n)&&a.drawn)a.drawn=!1,m[i.id].push(a)});i.drawn=!0}0<h.length&&d.fx.plot();for(j in m)g.each(m[j],function(a){a.drawn=!0});for(j=0;j<h.length;j++)i=h[j],f.save(),d.fx.plotSubtree(i,b,a,c),f.restore()},getSiblings:function(a){var b=
{};g.each(a,function(a){var d=a.getParents();if(0==d.length)b[a.id]=[a];else{var e=[];d[0].eachSubnode(function(a){e.push(a)});b[a.id]=e}});return b}});$jit.ST.Geom=new i({Implements:l.Geom,switchOrientation:function(a){this.config.orientation=a},dispatch:function(){var a=Array.prototype.slice.call(arguments),b=a.shift(),c=a.length,d=function(a){return"function"==typeof a?a():a};if(2==c)return"top"==b||"bottom"==b?d(a[0]):d(a[1]);if(4==c)switch(b){case "top":return d(a[0]);case "right":return d(a[1]);
case "bottom":return d(a[2]);case "left":return d(a[3])}},getSize:function(a,b){var c=a.data,d=this.config,e=d.siblingOffset,c=d.multitree&&"$orn"in c&&c.$orn||d.orientation,d=a.getData("width")+e,e=a.getData("height")+e;return b?this.dispatch(c,d,e):this.dispatch(c,e,d)},getTreeBaseSize:function(a,b,c){var d=this.getSize(a,!0),e=0,f=this;if(c(b,a))return d;if(0===b)return 0;a.eachSubnode(function(a){e+=f.getTreeBaseSize(a,b-1,c)});return(d>e?d:e)+this.config.subtreeOffset},getEdge:function(a,b,c){var d=
function(b,c){return function(){return a.pos.add(new o(b,c))}},e=this.node,f=a.getData("width"),g=a.getData("height");if("begin"==b){if("center"==e.align)return this.dispatch(c,d(0,g/2),d(-f/2,0),d(0,-g/2),d(f/2,0));if("left"==e.align)return this.dispatch(c,d(0,g),d(0,0),d(0,0),d(f,0));if("right"==e.align)return this.dispatch(c,d(0,0),d(-f,0),d(0,-g),d(0,0));throw"align: not implemented";}if("end"==b){if("center"==e.align)return this.dispatch(c,d(0,-g/2),d(f/2,0),d(0,g/2),d(-f/2,0));if("left"==e.align)return this.dispatch(c,
d(0,0),d(f,0),d(0,g),d(0,0));if("right"==e.align)return this.dispatch(c,d(0,-g),d(0,0),d(0,0),d(-f,0));throw"align: not implemented";}},getScaledTreePosition:function(a,b){var c=this.node,d=a.getData("width"),e=a.getData("height"),f=this.config.multitree&&"$orn"in a.data&&a.data.$orn||this.config.orientation,g=function(c,d){return function(){return a.pos.add(new o(c,d)).$scale(1-b)}};if("left"==c.align)return this.dispatch(f,g(0,e),g(0,0),g(0,0),g(d,0));if("center"==c.align)return this.dispatch(f,
g(0,e/2),g(-d/2,0),g(0,-e/2),g(d/2,0));if("right"==c.align)return this.dispatch(f,g(0,0),g(-d,0),g(0,-e),g(0,0));throw"align: not implemented";},treeFitsInCanvas:function(a,b,c){b=b.getSize();b=this.dispatch(this.config.multitree&&"$orn"in a.data&&a.data.$orn||this.config.orientation,b.width,b.height);return this.getTreeBaseSize(a,c,function(a,b){return 0===a||!b.anySubnode()})<b}});$jit.ST.Plot=new i({Implements:l.Plot,plotSubtree:function(a,b,c,d){var e=this.viz,f=e.canvas,h=e.config,c=Math.min(Math.max(0.001,
c),1);0<=c&&(a.drawn=!1,f=f.getCtx(),e=e.geom.getScaledTreePosition(a,c),f.translate(e.x,e.y),f.scale(c,c));this.plotTree(a,g.merge(b,{withLabels:!0,hideLabels:!!c,plotSubtree:function(){var b=h.multitree&&!("$orn"in a.data),c=b&&a.getData("orns");return!b||c.indexOf(a.getData("orn"))>-1}}),d);0<=c&&(a.drawn=!0)},getAlignedPos:function(a,b,c){var d=this.node;if("center"==d.align)a={x:a.x-b/2,y:a.y-c/2};else if("left"==d.align)d=this.config.orientation,a="bottom"==d||"top"==d?{x:a.x-b/2,y:a.y}:{x:a.x,
y:a.y-c/2};else if("right"==d.align)d=this.config.orientation,a="bottom"==d||"top"==d?{x:a.x-b/2,y:a.y-c}:{x:a.x-b,y:a.y-c/2};else throw"align: not implemented";return a},getOrientation:function(a){var b=this.config,c=b.orientation;b.multitree&&(b=a.nodeFrom,a=a.nodeTo,c="$orn"in b.data&&b.data.$orn||"$orn"in a.data&&a.data.$orn);return c}});$jit.ST.Label={};$jit.ST.Label.Native=new i({Implements:l.Label.Native,renderLabel:function(a,b){var c=a.getCtx(),d=b.pos.getc(!0),e=b.getData("width"),f=b.getData("height"),
d=this.viz.fx.getAlignedPos(d,e,f);c.fillText(b.name,d.x+e/2,d.y+f/2)}});$jit.ST.Label.DOM=new i({Implements:l.Label.DOM,placeLabel:function(a,b,c){var d=b.pos.getc(!0),e=this.viz.config,f=e.Node,g=this.viz.canvas,i=b.getData("width"),k=b.getData("height"),l=g.getSize(),n=d.x*g.scaleOffsetX+g.translateOffsetX,d=d.y*g.scaleOffsetY+g.translateOffsetY;if("center"==f.align)i={x:Math.round(n-i/2+l.width/2),y:Math.round(d-k/2+l.height/2)};else if("left"==f.align)e=e.orientation,i="bottom"==e||"top"==e?
{x:Math.round(n-i/2+l.width/2),y:Math.round(d+l.height/2)}:{x:Math.round(n+l.width/2),y:Math.round(d-k/2+l.height/2)};else if("right"==f.align)e=e.orientation,i="bottom"==e||"top"==e?{x:Math.round(n-i/2+l.width/2),y:Math.round(d-k+l.height/2)}:{x:Math.round(n-i+l.width/2),y:Math.round(d-k/2+l.height/2)};else throw"align: not implemented";k=a.style;k.left=i.x+"px";k.top=i.y+"px";k.display=this.fitsInCanvas(i,g)?"":"none";c.onPlaceLabel(a,b)}});$jit.ST.Label.SVG=new i({Implements:[$jit.ST.Label.DOM,
l.Label.SVG],initialize:function(a){this.viz=a}});$jit.ST.Label.HTML=new i({Implements:[$jit.ST.Label.DOM,l.Label.HTML],initialize:function(a){this.viz=a}});$jit.ST.Plot.NodeTypes=new i({none:{render:g.empty,contains:g.lambda(!1)},circle:{render:function(a,b){var c=a.getData("dim"),d=this.getAlignedPos(a.pos.getc(!0),c,c),c=c/2;this.nodeHelper.circle.render("fill",{x:d.x+c,y:d.y+c},c,b)},contains:function(a,b){var c=a.getData("dim"),d=this.getAlignedPos(a.pos.getc(!0),c,c),c=c/2;this.nodeHelper.circle.contains({x:d.x+
c,y:d.y+c},b,c)}},square:{render:function(a,b){var c=a.getData("dim"),d=c/2,c=this.getAlignedPos(a.pos.getc(!0),c,c);this.nodeHelper.square.render("fill",{x:c.x+d,y:c.y+d},d,b)},contains:function(a,b){var c=a.getData("dim"),d=this.getAlignedPos(a.pos.getc(!0),c,c),c=c/2;this.nodeHelper.square.contains({x:d.x+c,y:d.y+c},b,c)}},ellipse:{render:function(a,b){var c=a.getData("width"),d=a.getData("height"),e=this.getAlignedPos(a.pos.getc(!0),c,d);this.nodeHelper.ellipse.render("fill",{x:e.x+c/2,y:e.y+
d/2},c,d,b)},contains:function(a,b){var c=a.getData("width"),d=a.getData("height"),e=this.getAlignedPos(a.pos.getc(!0),c,d);this.nodeHelper.ellipse.contains({x:e.x+c/2,y:e.y+d/2},b,c,d)}},rectangle:{render:function(a,b){var c=a.getData("width"),d=a.getData("height"),e=this.getAlignedPos(a.pos.getc(!0),c,d);this.nodeHelper.rectangle.render("fill",{x:e.x+c/2,y:e.y+d/2},c,d,b)},contains:function(a,b){var c=a.getData("width"),d=a.getData("height"),e=this.getAlignedPos(a.pos.getc(!0),c,d);this.nodeHelper.rectangle.contains({x:e.x+
c/2,y:e.y+d/2},b,c,d)}}});$jit.ST.Plot.EdgeTypes=new i({none:g.empty,line:{render:function(a,b){var c=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,f=d._depth<e._depth,g=this.viz.geom.getEdge(f?d:e,"begin",c),c=this.viz.geom.getEdge(f?e:d,"end",c);this.edgeHelper.line.render(g,c,b)},contains:function(a,b){var c=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,f=d._depth<e._depth,g=this.viz.geom.getEdge(f?d:e,"begin",c),c=this.viz.geom.getEdge(f?e:d,"end",c);return this.edgeHelper.line.contains(g,c,
b,this.edge.epsilon)}},arrow:{render:function(a,b){var c=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,f=a.getData("dim"),g=this.viz.geom.getEdge(d,"begin",c),c=this.viz.geom.getEdge(e,"end",c),e=a.data.$direction;this.edgeHelper.arrow.render(g,c,f,e&&1<e.length&&e[0]!=d.id,b)},contains:function(a,b){var c=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,f=d._depth<e._depth,g=this.viz.geom.getEdge(f?d:e,"begin",c),c=this.viz.geom.getEdge(f?e:d,"end",c);return this.edgeHelper.arrow.contains(g,c,b,this.edge.epsilon)}},
"quadratic:begin":{render:function(a,b){var c=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,f=d._depth<e._depth,g=this.viz.geom.getEdge(f?d:e,"begin",c),d=this.viz.geom.getEdge(f?e:d,"end",c),e=a.getData("dim"),f=b.getCtx();f.beginPath();f.moveTo(g.x,g.y);switch(c){case "left":f.quadraticCurveTo(g.x+e,g.y,d.x,d.y);break;case "right":f.quadraticCurveTo(g.x-e,g.y,d.x,d.y);break;case "top":f.quadraticCurveTo(g.x,g.y+e,d.x,d.y);break;case "bottom":f.quadraticCurveTo(g.x,g.y-e,d.x,d.y)}f.stroke()}},"quadratic:end":{render:function(a,
b){var c=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,f=d._depth<e._depth,g=this.viz.geom.getEdge(f?d:e,"begin",c),d=this.viz.geom.getEdge(f?e:d,"end",c),e=a.getData("dim"),f=b.getCtx();f.beginPath();f.moveTo(g.x,g.y);switch(c){case "left":f.quadraticCurveTo(d.x-e,d.y,d.x,d.y);break;case "right":f.quadraticCurveTo(d.x+e,d.y,d.x,d.y);break;case "top":f.quadraticCurveTo(d.x,d.y-e,d.x,d.y);break;case "bottom":f.quadraticCurveTo(d.x,d.y+e,d.x,d.y)}f.stroke()}},bezier:{render:function(a,b){var c=this.getOrientation(a),
d=a.nodeFrom,e=a.nodeTo,f=d._depth<e._depth,g=this.viz.geom.getEdge(f?d:e,"begin",c),d=this.viz.geom.getEdge(f?e:d,"end",c),e=a.getData("dim"),f=b.getCtx();f.beginPath();f.moveTo(g.x,g.y);switch(c){case "left":f.bezierCurveTo(g.x+e,g.y,d.x-e,d.y,d.x,d.y);break;case "right":f.bezierCurveTo(g.x-e,g.y,d.x+e,d.y,d.x,d.y);break;case "top":f.bezierCurveTo(g.x,g.y+e,d.x,d.y-e,d.x,d.y);break;case "bottom":f.bezierCurveTo(g.x,g.y-e,d.x,d.y+e,d.x,d.y)}f.stroke()}}})})();
